### ISSUE TITLE
Add hot-reload

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#1]
Make it auto-refresh when you save

**Comment by Anuran12** [comment]
@acidmaksim I would like to give it a try

**Comment by movmovbaby** [comment]
@acidmaksim к кому можно обратиться за советом по реализации хотрелоуда?

**Comment by LarendsD** [comment]
@acidmaksim, в итоге этот ишью взяли? Появилась идея для реализации, если не занято, могу взять

**Comment by fey** [comment]
@LarendsD бери)

**Comment by dzencot** [comment]
По идее уже был `make start-frontend`, ну да ладно

**Comment by LarendsD** [comment]
Да не, тот то работал как хотрелоад только для фронтенда) А этот работает как хотрелоад для бекенда и для фронтенда в одном) Так назвал просто потому что я просто по сути добавил в старый конфиг для хот-релоада на бекенде, конфиг для хотрелоада на фронтенде

**Comment by LarendsD** [comment]
Рассматривал этот вариант, там для этого нужен плагин для реакта, и он работает только в том случае, когда запускаешь конфиг вебпака с webpack serve, но тогда запускается ещё один сервер, уже фронтендовский, и он перекроет запуск бекенда и работать будет получается только фронтовая часть.

**Comment by acidmaksim** [comment]
@dzencot еще актуально?

**Comment by fey** [comment]
@semenChe можно вот этот ишшус проверить. Если хот релоад работает (на бекенде, фротенде) - можно закрывать.

**Comment by fey** [comment]
@boldurean Можно вот этот ишшус проверить.

**Comment by ssssank** [comment]
@boldurean ну как оно? работает? :)

**Comment by boldurean** [comment]
> @boldurean ну как оно? работает? :)

Пока, над окном редактора появляется строка что-то вроде "Не сохраненных изменений нет" для меня странно если честно. Поэтому в другом ишью мы обсуждали как бы это улучшить.

**Comment by fey** [comment]
А тут задачка вроде бы про другое. Про то, что раньше необходимо было пересобирать приложение.

**Comment by ssssank** [comment]
Вот я тоже сидел, размышлял, правильно ли я понял этот ишью или нет :upside_down_face:
