### ISSUE TITLE
Поправить стили на странице восстановления пароля 

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#105]
https://runit.hexlet.ru/remind_password

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/77053797/205650625-c0958003-6e24-48b7-ad07-cbd78aa46aae.png">

**Comment by acidmaksim** [comment]
@Difuster как успехи с задачей?

**Comment by vladikKir** [comment]
Беру в работу, если актуальна
