### ISSUE TITLE
Привести к одному стилю модалку 

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#110]
Эту модалку можно открыть по кнопке "поделиться" на странице сниппета. Она выглядит не в стиле проекта, нужно это исправить

<img width="592" alt="image" src="https://user-images.githubusercontent.com/77053797/206651711-68e9da42-0143-421f-9175-63f2ba190aa1.png">

**Comment by Blinina** [comment]
Взяла вработу.)

**Comment by denikeev** [comment]
беру в работу

**Comment by denikeev** [comment]
отправил пул реквест https://github.com/hexlet-rus/runit/pull/127
