### ISSUE TITLE
Добавить “Лицензионное соглашение для некоммерческого использования“

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#115]
Вместо "Публичная оферта" в подвале, нужно сделать страницу “Лицензионное соглашение для некоммерческого использования“. 
Текст лицензии в документе. 

Также нужно указать город Ульяновск, как на скрине и дату 13.12.2022

![image](https://user-images.githubusercontent.com/77053797/207328351-1cb32511-340a-40bb-96e1-1f14b5ae4e5b.png)
[AGPL3 - Русская.docx](https://github.com/hexlet-rus/runit/files/10218212/AGPL3.-.docx)

**Comment by Mansur903** [comment]
Возьму в работу
