### ISSUE TITLE
Изменить путь у кнопки "Начать кодить"

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#118]
Сейчас при нажатии на кнопку "Начать кодить", на втором экране лэндинга,  она ведет на регистрацию, а должна вести в создание сниппета. Нужно исправить 
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/77053797/207797479-62262101-83c4-4940-8f00-f8f9c0c3c0d9.png">

**Comment by acidmaksim** [comment]
@antonkrupin как успехи с задачей?

**Comment by antonkrupin** [comment]
я PR уже давно отправил, вроде даже приняли его.
