### ISSUE TITLE
На странице регистрации нужно убрать раздел профиль

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#119]
![image](https://user-images.githubusercontent.com/77053797/207798013-ba397ce8-7389-43d6-8ea5-60a20a7bcbd4.png)

**Comment by antonkrupin** [comment]
беру в работу

**Comment by Zubkov99** [comment]
Взял в работу

**Comment by acidmaksim** [comment]
@antonkrupin @Zubkov99 кто то сделал эту задачу?

**Comment by antonkrupin** [comment]
я не приступал, так как задачу передали другому человеку.
