### ISSUE TITLE
Изменить название

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#125]
Нужно проверить на всех страницах название, где есть Runit и переписать в Run IT.
 
Для примера, как сейчас сделано в шапке, а также на лэнде: 
<img width="276" alt="image" src="https://user-images.githubusercontent.com/77053797/208862656-d1bcf0bf-c960-4dab-9456-f5b7c5860214.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/77053797/208862859-142319c5-0cca-4a5e-9f8d-7f4aa261bb1a.png">

**Comment by EgorUlitin** [comment]
Беру
