### ISSUE TITLE
Изменить текст заголовка и футера

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#140]
Изменить заголовок на "Бесплатный* проект Хекслета"
<img width="389" alt="image" src="https://user-images.githubusercontent.com/77053797/211609575-bdc5b627-841d-40cc-ad6f-7c9aa31289f1.png">

А сноску в футере сделать такой:

*Бесплатно для некоммерческого использования:
"Лицензионное соглашение для некоммерческого использования" изменить на "Некоммерческое лицензионное соглашение"
![image](https://user-images.githubusercontent.com/77053797/211610449-19e02f9e-8f07-4e4e-aa5b-f1996ed1231c.png)

**Comment by vladikKir** [comment]
беру в работу

**Comment by vladikKir** [comment]
Сделал пулреквест

**Comment by acidmaksim** [comment]
С этим ишью пока нужно подождать, когда определимся с лицензией переоткроем задачу.

**Comment by acidmaksim** [comment]
[#](https://github.com/hexlet-rus/runit/pull/142)
