### ISSUE TITLE
Поправить пути у кнопок на лендинге

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#143]
Так как мы делаем похожий сервис на Replit, то нужно исправить путь у первой и второй кнопки на лендинге на https://runit.hexlet.ru/login

Так как логично, что сервисом могут пользоваться только авторизованные пользователи. 

![image](https://user-images.githubusercontent.com/77053797/211809750-e8fc8e83-a6ef-4a56-8e8e-928655fafdd1.png)
![image](https://user-images.githubusercontent.com/77053797/211785264-6d1e39b5-5bc5-470d-ae50-5945ea71c83e.png)

**Comment by vladikKir** [comment]
взял в работу
