### ISSUE TITLE
Добавить текст на лендинг

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#145]
Текст, который нужно добавить: 
"ПО распространяется в виде интернет-сервиса (SaaS-решение), специальные действия
по установке по на стороне пользователя не требуются"

Его нужно добавить в самый низ лендинга, просто текстом с соблюдением стилей лендинга. 
![image](https://user-images.githubusercontent.com/77053797/211805264-8f8b6617-e1eb-403f-bbcb-60a7b14af6f6.png)

**Comment by vladikKir** [comment]
взял в работу

**Comment by acidmaksim** [comment]
https://github.com/hexlet-rus/runit/pull/149
