### ISSUE TITLE
Изменить путь до переводчика в компонентах.

### ISSUE THREAD

**Issue by vladikKir** [hexlet-rus/runit#150]
Например, в Faq.jsx можно использовать хук useTranslation так, чтобы вместо 'faq.a1' и т.д писать 'a1'. Аналогично по другим компонентам.

**Comment by dzencot** [comment]
А как это хочешь сделать, брать имя компонента, чтобы оно в lowerCase подставлялся автоматом перед ключом? Или уже есть готовые инструменты под это?

**Comment by vladikKir** [comment]
Подобную конструкцию в проекте чата использую:
const { t } = useTranslation('translation', { keyPrefix: 'faq' })

**Comment by dzencot** [comment]
Просто я думаю, что текст не обязательно может быть по компонентам разбить. В переводах он может разделяться по одному принципу, а в компонентах использовваться по другому

**Comment by fey** [comment]
@dzencot это актуальная задачка, будем делать?

**Comment by VictoryPashkova** [comment]
Взяла задачу
