### ISSUE TITLE
Реализовать автосохранение сниппета

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#155]
Сейчас при редактировании сниппета код сохраняется по кнопке "Запустить".

Нужно сделать так, чтобы после написания кода он автоматически сохранялся через пару секунд и это было видно с помощью этой надписи: 
![image](https://user-images.githubusercontent.com/77053797/212148077-85942a6c-07bc-405e-8678-572dd4bab362.png)

**Comment by Takaiva** [comment]
Берусь за работу!

**Comment by AnastasiaKv** [comment]
беру

**Comment by AnastasiaKv** [comment]
pr #220

**Comment by boldurean** [comment]
Автосохранение работает. Можно закрывать. 
По поводу изменений уведомления еще вроде как говорится [тут](https://github.com/hexlet-rus/runit/issues/222)

**Comment by fey** [comment]
Спасибки
