### ISSUE TITLE
Нужно добавить шаблоны для issues

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#159]
Нужно сделать 3 шаблона для issues на английском языке, чтобы было удобнее удобнее и понятнее оформлять задачи. Пример можно найти на [Hexlet-SICP](https://github.com/Hexlet/hexlet-sicp/blob/main/.github/ISSUE_TEMPLATE/bugreport.yml) 

Bug - это описание какой либо ошибки найденной на сайте. Шаблон полностью можно скопировать из [Hexlet-SICP](https://github.com/Hexlet/hexlet-sicp/blob/main/.github/ISSUE_TEMPLATE/bugreport.yml)

Feature request - это изменения предлагаемые студентами по улучшению и доработкам проекта. По дефолту должен стоять лэйбл "feature request" и должно быть два пункта:

- Problem description
- Proposed solution

Task -  это задачи, которые добавляют сотрудники Хекслета. По дефолту должен стоять лэйбл "task" и три пункта: 

- Problem description
- Proposed solution
- Solution

**Comment by JS-Samurai** [comment]
Попробую сделать
