### ISSUE TITLE
Bug: Проверить все кнопки, ссылки, которые ведут на открытие сниппета.

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#169]
### Summary

Нужно проверить работоспособность новых роутов в приложении. Мы сделали ресурсный роутинг, но при тестировании всплывали ошибки. Нужно их отловить и исправить. 

### Reproduction steps

```bash
Проверить все кнопки, ссылки, которые ведут на открытие сниппета. Проверить что они ведут на открытие снипета по новому роутингу.
```

### Expected result

Переделать на новый, где надо.  Новый: /{username}/snippets/{slug}

### Actual result

Старый: /editor?snippet={id}

**Comment by AnastasiaKv** [comment]
Беру

**Comment by AnastasiaKv** [comment]
pr #173

**Comment by AnastasiaKv** [comment]
pr #175

**Comment by AnastasiaKv** [comment]
pr #205
