### ISSUE TITLE
Bug: Исправить дублирование сниппетов

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#170]
### Summary

При взаимодействии с интерфейсом дублируются сниппеты в профиле. Нужно это исправить

### Reproduction steps

```bash
Действия: зайти в профиль, создать снипет, перейти на другую вкладку (например "о проекте"), вернуться в профиль - появятся дубли.
```

### Expected result

Избавиться от дублирования сниппетов

### Actual result

Сейчас есть дубли сниппетов при шагах выше

**Comment by AnastasiaKv** [comment]
pr #172

**Comment by AnastasiaKv** [comment]
@acidmaksim, pr был принят, можно ли закрыть текущий issue?

**Comment by boldurean** [comment]
Вроде можно закрывать.
