### ISSUE TITLE
Fix slug generation

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#174]
### Problem description

В текущем виде, если у пользователь меняет название сниппета, то может поменяться название сниппета.
В этом плане ломается возможность делиться кодом (встраивание и по ссылке).
Здесь можно повторить поведение у codepen, когда мы генерирует slug из рандомных букв и не меняем. Название сниппета отвязывается от слага.
Будет ссылка вида
https://runit.hexlet.ru/users/feycot/snippets/AdaAsd

### Proposed solution

Изменить поведение генерации slug, запретить его менять пользователям.
Пользователь может поменять название сниппета, но не его slug (url)
Для пользователя по прежнему генерируется имя сниппета, но оно на слаг не влияет.

### Solution

-

**Comment by AnastasiaKv** [comment]
В работе

**Comment by AnastasiaKv** [comment]
Issue был решен в процессе работы на другой задачей (pr #205).

**Comment by boldurean** [comment]
Тоже кажется решено.
