### ISSUE TITLE
Bug: не работает вставка кода через iframe

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#176]
### Summary

Сейчас перестал работать код, который вставляется на страницу через iframe.

### Reproduction steps

```bash
1. Зайти к себе в профиль
2. Нажать на кнопку поделиться
3. Выбрать код для вставки
4. Скопировать код и попытаться вставить его на любую страницу
```

### Expected result

Раньше код работал. Нужно починить это и сделать так, чтобы вставленный код открывался на других страницах. 

### Actual result

Вот так вставленный код выглядит сейчас
<img width="958" alt="image" src="https://user-images.githubusercontent.com/77053797/215521204-5d1d6f94-8877-4bd0-aa5f-5e76b1ef497e.png">

### Browsers

Chrome

### OS

Mac

**Comment by acidmaksim** [comment]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/77053797/215523181-ae0be3c4-90dd-405a-903f-d7e973054edb.png">

**Comment by AnastasiaKv** [comment]
беру в работу

**Comment by AnastasiaKv** [comment]
pr #214

**Comment by redaktorscha** [comment]
![image](https://user-images.githubusercontent.com/39005857/231108905-66243c28-4c83-462e-8b1f-c9cd4068fe52.png)
 Вроде работает все
