### ISSUE TITLE
Bug: Не подсвечивается красным цветом поле при вводе некорректной почты на странице "Забыли пароль?"

### ISSUE THREAD

**Issue by Germankhz** [hexlet-rus/runit#179]
### Summary

Не подсвечивается красным цветом поле при вводе некорректной почты на странице "Забыли пароль?"

### Reproduction steps

```bash
1. Открыть страницу веб-приложения https://runit.hexlet.ru/remind_password
2. Вставить в поле "Электронная почта" example/smile.ru
3. Нажать Tab
```

### Expected result

Поле "Электронная почта" подсвечивается красным цветом.

### Actual result

Поле "Электронная почта" **НЕ подсвечивается красным цветом**.

### Browsers

Chrome

### OS

Windows

**Comment by YuliaMisc** [comment]
Попробую сделать.
