### ISSUE TITLE
Bug: Не подсвечивается красным цветом поле при вводе незарегистрированной почты на странице "Забыли пароль?"

### ISSUE THREAD

**Issue by Germankhz** [hexlet-rus/runit#180]
### Summary

Не подсвечивается красным цветом поле при вводе незарегистрированной почты на странице "Забыли пароль?"

### Reproduction steps

```bash
1. Открыть страница веб-приложения https://runit.hexlet.ru/remind_password
2. Вставить в поле "Электронная почта" example@smile.ru
3. Нажать кнопку "Восстановить пароль"
```

### Expected result

Поле "Электронная почта" подсвечивается красным цветом.

### Actual result

Поле "Электронная почта" **НЕ подсвечивается красным цветом**.

### Browsers

Chrome

### OS

Windows

**Comment by antonDedyaev** [comment]
Возьму в работу

**Comment by artch3r** [comment]
@semenChe , добрый день!

Подскажите пожалуйста, задача у вас в работе?)

**Comment by artch3r** [comment]
@semenChe , добрый день!
Подскажите пожалуйста, задача у вас в работе? Или можно взять?))

**Comment by fey** [comment]
ага, мы пользователю не говорим, есть такая почта или нет. Это уже потом проверяется
