### ISSUE TITLE
Bug: Не выводится сообщение об ошибке "Некорректная электронная почта" при вводе некорректной почты на странице "Вход".

### ISSUE THREAD

**Issue by Germankhz** [hexlet-rus/runit#181]
### Summary

Не выводится сообщение об ошибке "Некорректная электронная почта" при вводе некорректной почты на странице "Вход".

### Reproduction steps

```bash
1. Открыть страницу веб-приложения https://runit.hexlet.ru/login
2. Вставить в поле "Электронная почта" example/smile.ru
3. Нажать Tab
```

### Expected result

Снизу от поля "Электронная почта" выводится сообщение об ошибке.

### Actual result

Снизу от поля "Электронная почта" **НЕ выводится сообщение об ошибке**.

### Browsers

Chrome

### OS

Windows

**Comment by MikRyam** [comment]
Я взял в работу
