### ISSUE TITLE
Bug: Не выводится сообщение об ошибке при вводе незарегистрированной почты на странице "Забыли пароль?"

### ISSUE THREAD

**Issue by Germankhz** [hexlet-rus/runit#182]
### Summary

Не выводится сообщение об ошибке при вводе незарегистрированной почты на странице "Забыли пароль?"

### Reproduction steps

```bash
1. Открыть страница веб-приложения https://runit.hexlet.ru/remind_password
2. Вставить в поле "Электронная почта" example@smile.ru
3. Нажать кнопку "Восстановить пароль"
```

### Expected result

Снизу от поля "Электронная почта" выводится сообщение об ошибке.

### Actual result

Снизу от поля "Электронная почта" **НЕ выводится сообщение об ошибке**.

### Browsers

Chrome

### OS

Windows

**Comment by VikkyAblaeva** [comment]
Попробую разобраться

**Comment by semenChe** [comment]
Здравствуйте) @VikkyAblaeva  работаешь над этим?
Я могу сделать в короткие сроки)
Один вопрос: Подскажите какой запрос на сервер нужно сделать для проверки того, существует эта почта в списке зарегистрированных пользователей или нет??

**Comment by fey** [comment]
Логика какая должна быть - пользователь вводит пароль и ему выводится сообщение типа "Если данная почта зарегистрирована, вы получите письмо". 
Проверки на наличие почты НЕ  должно быть.
Должна быть валидация на форме, что мы ввели верный почтовый аккаунт
А так да, фронтенд не подключен. На сервере пока нет отправки писем.

**Comment by semenChe** [comment]
В таком случае это я сделаю сегодня)

**Comment by semenChe** [comment]
Хотя нужно подождать когда будет backend под это готов) Не обманывать же пользователей этим сообщением)

**Comment by fey** [comment]
Давай тогда скроем ссылки а восстановление пароля

**Comment by semenChe** [comment]
Могу это сделать (подразумевается чтобы на странице авторизации небыло ссылки "Не помню пароль". Я правильно понимаю?)

**Comment by fey** [comment]
да, спрятать, пока не работает.

**Comment by semenChe** [comment]
Сделаю это)

**Comment by semenChe** [comment]
отправил pr
