### ISSUE TITLE
Bug: Не подсвечивается красным поле "Электронная почта" при вводе некорректной почты на странице "Вход".

### ISSUE THREAD

**Issue by Germankhz** [hexlet-rus/runit#183]
### Summary

Не подсвечивается красным поле "Электронная почта" при вводе некорректной почты на странице "Вход".

### Reproduction steps

```bash
1. Открыть страницу веб-приложения https://runit.hexlet.ru/login
2. Вставить в поле "Электронная почта" example/smile.ru
3. Нажать Tab
```

### Expected result

Поле "Электронная почта" подсвечивается красным.

### Actual result

Поле "Электронная почта" **НЕ подсвечивается красным**.

### Browsers

Chrome

### OS

Windows

**Comment by MikRyam** [comment]
Я взял в работу
