### ISSUE TITLE
Bug: Не подсвечивается красным поле "Логин" при вводе недопустимых символов

### ISSUE THREAD

**Issue by Germankhz** [hexlet-rus/runit#184]
### Summary

До нажатия кнопки "Отправить" не подсвечивается красным поле "Логин" при вводе недопустимых символов во всплывающем окне "Редактирование" на странице "Профиль"

### Reproduction steps

```bash
1. Произвести вход в учетную запись: 
       email: user01@mail.ru
       password: 123456789
2. Нажать кнопку "Профиль" ( открыть страницу https://runit.hexlet.ru/profile )
3. Нажать кнопку "Редактировать"
4. Во всплывающем окне в поле "Логин" ввести "user01"
```

### Expected result

Поле "Логин" подсвечивается красным.

### Actual result

Поле "Логин" **НЕ подсвечивается красным**.

### Browsers

Chrome

### OS

Windows

**Comment by MikRyam** [comment]
А недопустимые символы - это какие? Цифры? Всё кроме букв?

**Comment by Germankhz** [comment]
> А недопустимые символы - это какие? Цифры? Всё кроме букв?

![Снимок1](https://user-images.githubusercontent.com/119713022/216572996-0126794d-e8bd-4214-a3fe-2f5d6b3d1746.JPG)

Требования к логину на странице регистрации вот такие, отсюда делаю вывод что требования в рассматриваемом  случае аналогичные

**Comment by MikRyam** [comment]
Ok. Спасибо. Беру в работу.

**Comment by redaktorscha** [comment]
Это уже пофиксено? [И вот это тоже](https://github.com/hexlet-rus/runit/issues/185)
![image](https://user-images.githubusercontent.com/39005857/231115467-5f17d032-96c0-421f-9d1f-82fafedab7aa.png)
