### ISSUE TITLE
Bug: Не выводится сообщение об ошибке при вводе недопустимых символов в поле "Логин"

### ISSUE THREAD

**Issue by Germankhz** [hexlet-rus/runit#185]
### Summary

До нажатия кнопки "Отправить" не выводится сообщение об ошибке при вводе недопустимых символов в поле "Логин" во всплывающем окне "Редактирование" на странице "Профиль".

### Reproduction steps

```bash
1. Произвести вход в учетную запись 
       email: user01@mail.ru
       password: 123456789
2. Нажать кнопку "Профиль" ( открыть страницу https://runit.hexlet.ru/profile )
3. Нажать кнопку "Редактировать"
4. Во всплывающем окне в поле "Логин" ввести "user01"
5. Нажать Tab
```

### Expected result

Снизу от поля "Логин" выводится сообщение об ошибке.

### Actual result

Снизу от поля "Логин" **НЕ выводится сообщение об ошибке**.

### Browsers

Chrome

### OS

Windows

**Comment by MikRyam** [comment]
Беру в работу.

**Comment by boldurean** [comment]
Можно закрывать?
