### ISSUE TITLE
Bug: Не работает кнопка "Скопировать ссылку" на странице "Профиль".

### ISSUE THREAD

**Issue by Germankhz** [hexlet-rus/runit#186]
### Summary

При нажатии на кнопку "скопировать ссылку" на странице профиля пользователя **ничего не происходит**.

### Reproduction steps

```bash
1. Произвести вход в учетную запись 
       email: user01@mail.ru
       password: 123456789
2. Открыть профиль пользователя нажав кнопку "Профиль" (страницу https://runit.hexlet.ru/profile)
3. Нажать кнопку "Скопировать ссылку"
4. Открыть новую вкладку браузера
5. В адресную строку вставить адрес скопированной ссылки
```

### Expected result

В адресную строку вставляется адрес скопированной ссылки.

### Actual result

В адресную строку **НЕ вставляется адрес скопированной ссылки.**

### Browsers

Chrome

### OS

Windows

**Comment by PShorin** [comment]
Беру в работу!

**Comment by PShorin** [comment]
Не могу войти в Профиль. Ввожу все данные и система не пускает дальше
<img width="516" alt="image" src="https://user-images.githubusercontent.com/107258045/218168782-4a2cbfce-a58d-4612-aaac-aa1d42be0580.png">

**Comment by Germankhz** [comment]
> Не могу войти в Профиль. Ввожу все данные и система не пускает дальше 

Странно, у меня логинится нормально! проверьте еще раз все вводимые данные. Если не получится, то попробуйте зарегать собственного пользователя и зайти под ним. Суть не изменится.

**Comment by PShorin** [comment]
> логинится

Кнопка ВОЙТИ и ЗАРЕГИСТРИРОВАТЬСЯ  просто не работает.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/107258045/218247130-02d1337e-68f2-4bf9-a91b-0c043588f0d4.png">
я не могу перейти дальше, не понимаю почему

**Comment by PShorin** [comment]
и вот так пишет в консоли 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/107258045/218247164-b44527a3-a2e7-493d-bcad-5ca7687b5722.png">

**Comment by PShorin** [comment]
Решил данную проблему, сейчас отправлю PR

**Comment by PShorin** [comment]
Отправил PR

**Comment by boldurean** [comment]
можно закрывать?

**Comment by PShorin** [comment]
да, проблема решена
