### ISSUE TITLE
Добавить отправку ошибок в Sentry

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#19]
Добавить логирование с sentry

**Comment by BelarusWillBeFree** [comment]
I take this task!

**Comment by acidmaksim** [comment]
@BelarusWillBeFree сделал?

**Comment by Evgen-Polyanskii** [comment]
@acidmaksim Если необходимо, то я могу взять эту задачу.

**Comment by acidmaksim** [comment]
@Evgen-Polyanskii если @BelarusWillBeFree в течении пары дней не ответит, то бери

**Comment by Evgen-Polyanskii** [comment]
@acidmaksim К сожалению, я не могу выполнить эту задачу. Не хватает времени

**Comment by movmovbaby** [comment]
@acidmaksim sentry нужно добавить только во фронтендовую часть?

**Comment by movmovbaby** [comment]
@acidmaksim @fey взял задачу, оправил PR

**Comment by Viktorline** [comment]
Возьму в работу, постараюсь выполнить
