### ISSUE TITLE
Bug: Выход за границы колонки профиля логина в размере 20 символов.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-rus/runit#193]
### Summary

При редактировании логина в профиле пользователя или регистрации пользователя с логином в размере 20 символов, данный логин отображен некорректно.

![image](https://user-images.githubusercontent.com/102296858/216782787-6f2b145e-19bf-48d6-a1de-3cef64ec5266.png)

Test-data: "Логин" = 20 символов.

### Reproduction steps

```bash
Регистрация:
- Ввести электронную почту
- Ввести логин
- Ввести пароль
- Подтвердить пароль
- Нажать кнопку "Зарегистрироваться"

Изменение "Логин" существующего пользователя:
- Авторизоваться в приложении
- Нажать кнопку "Редактировать"
- Ввести логин
- Нажать кнопку "Отправить"
```

### Expected result

Логин из 20 символов отображен корректно.

### Actual result

Логин из 20 символов отображен некорректно.

### Browsers

Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Разрешение дисплея 2560х1600

**Comment by PShorin** [comment]
А корректно это как? Логин должен обрезаться на каком символе? То есть вот так? kkkkkkkkkkk... ?

**Comment by 2KO1** [comment]
Насчет корректности, возможно так чтобы весь логин не выходил за рамки поля "профиль", по поводу обрезки не нашел требований, на мой взгляд разумным будет, либо уменьшить количество допустимых символов в логине, либо расширить поле "профиль", чтобы все символы входили ровно. Может быть уменьшить размер шрифта логина, по той же причине. А обрезанный логин с многоточием как мне видится будет не информативным.

**Comment by PShorin** [comment]
Если я не ошибаюсь, то кто-то уже выполнил данный Issue и отправил PR

**Comment by redaktorscha** [comment]
Привет! Эту таску можно взять?
Если буквы у логина широкие, то он по-прежнему не лезет в поле
![image](https://user-images.githubusercontent.com/39005857/230765519-599149c6-34b5-499d-9f97-352ddef03710.png)

**Comment by fey** [comment]
@redaktorscha да, можно.
