### ISSUE TITLE
Bug: Изменение электронной почты на некорректную при редактировании в профиле пользователя.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-rus/runit#194]
### Summary

После авторизации, при редактировании электронной почты, можно изменить электронную почту на некорректную.

![image](https://user-images.githubusercontent.com/102296858/216783557-9b02fe83-a4c6-40a7-b612-3de2d87228b3.png)

### Reproduction steps

```bash
- Авторизоваться в приложении
- Нажать кнопку "Редактировать"
- Нажать кнопку "Отправить"
```

### Expected result

При вводе недопустимых символов, отображается сообщение об ошибке.

### Actual result

Программа изменяет электронную почту на некорректную.

### Browsers

Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Разрешение дисплея 2560х1600

**Comment by YuliaMisc** [comment]
Возьму в работу

**Comment by boldurean** [comment]
Вроде валидация работает. Нужно бы уведомить пользователя если такой email уже существует и показать соответствующее сообщение, но это уже другой ишью

**Comment by redaktorscha** [comment]
![image](https://user-images.githubusercontent.com/39005857/231106808-b09ec924-559d-4179-9b8a-ec31da596eed.png)
Это пофиксено, но я нашла вот такой баг: конкретно в этой форме у инпута type="email", поэтому можно ввести кириллический домен типа user@юзер.рф (или какой-нибудь другой юникод), и валидатор это пропустит, потому что получит уже punycode. Почта поменяется, а потом с ней будет не войти, потому что в формах signin/signup валидатор кириллицу уже не пропустит.

**Comment by fey** [comment]
@redaktorscha а если добавить валидацию и запретить кириллические символы на этой форме?

**Comment by redaktorscha** [comment]
@fey Там уже есть валидация, она такая же, как и в других формах. Проблема в том, что конкретно здесь в yup попадает уже сконвертированная строка. Не 'почта.рф', например, а 'xn--80a1acny.xn--p1ai'. Поэтому валидация проходит ок. B это делает сам Хром.
Пока ничего не могу придумать, кроме как убрать у инпута type="email", хотя жалко, т.к. с таким типом на мобилках более удобная клавиатура 
В других формах (регистрация, напоминание пароля) у инпутов с email нет типа email, поэтому такой проблемы не возникает.

**Comment by redaktorscha** [comment]
Ну или наоборот, инпутам в других формах добавить тоже тип email, если разрешены домены не только из  латинских символов

**Comment by fey** [comment]
Поизучай, пожалуйста, являются ли кириллические почтоые домены - валидными. Если да, то оставим тип email на формах регистрации и логина.

Кажется у нас была дискуссия про это и я не помню на чем остановились (надо посмотреть по коду. По-моему кастомный валидатор добавляли).

**Comment by redaktorscha** [comment]
привет! @fey 
поресерчила:
1. Internationalized Domain Names (IDN), т.е. юникодные доменные имена, считаются валидными. Это не только кириллица, но и иероглифы, диакритики и пр.  [Стандарт rfc6532, 2012 г.:](https://www.rfc-editor.org/rfc/rfc6532)

[Источник](https://unicode.org/faq/idn.html) утверждает, что IDN поддерживаются всеми современными браузерами и софтом для отправки email.

2. Домен "рф" существует с 2010 г., т.е. довольно давно. 
Reg.ru пишет, что  к 2019 г было зарегистрировано уже 800 тысяч доменов в зоне .рф.
Насчет распространенности кириллических доменов именно для почты сложно сделать какие-то выводы, но они вполне [валидные](https://en.wikipedia.org/wiki/International_email).
Нормальной статистики не нашлось. [Источник](https://www.comnews.ru/content/207063/2020-05-13/2020-w20/rf-nepopulyaren-strane-no-krupneyshiy-kirillicheskiy-domen-mire) пишет, что всего 0,3% доменов (из всех кириллических) используют для имейлов.

3. В любом случае, насколько я поняла, все IDN переводятся и хранятся в punycode, напр., "рф" кодируется как "xn--p1ai", и в конечном итоге получается последовательность ascii-символов

4. Есть проблема с тем, что браузеры на Хромиуме сразу переводят input value в punycode, а, например, Мозилла и Сафари - нет.

Я нашла и попробовала вот эту [депенденси](https://www.npmjs.com/package/punycode), вроде норм
Пока что я как-то так это себе представляю:
1) юзер вводит свою почту, она может быть ascii, а может быть юникод
2) в validationSchema  переводим input value в punycode в любом случае (yup.transform)
3) в профиле и в формах показываем юзеру обратно перекодированный unicode, потому что punycode выглядит странно
4) по сабмиту в БД улетает punycode, в стейте, получается, тоже будет punycode

**Comment by ssssank** [comment]
@fey предлагаю этот ишью закрыть и создать новый с добавлением доменов .рф и punycode

**Comment by fey** [comment]
ладно, давайте разрешим рф домены, только они должны преобразовываться, да.

**Comment by faciledictu** [comment]
Возьму в работу. Сделаю согласно алгоритму @redaktorscha 

> 1. юзер вводит свою почту, она может быть ascii, а может быть юникод
2. в validationSchema переводим input value в punycode в любом случае (yup.transform)
3. в профиле и в формах показываем юзеру обратно перекодированный unicode, потому что punycode выглядит странно
4. по сабмиту в БД улетает punycode, в стейте, получается, тоже будет punycode

**Comment by faciledictu** [comment]
По этому алгоритму изменения на бэке не предполагаются. Но мне кажется, и на стороне сервера должно быть ограничение на валидацию только ascii-почты даже в том случае, если туда будет отправляться только ascii. Сейчас сервер пропускает любую.
Да, придется во фронтэнд подключать дополнительную библиотеку, это утяжеляет. На сервере без разницы.

Хотя тогда, по идее, фронт может и юникод отправить, а сервер конвертирует. Может на сервере это все реализовать?)

**Comment by fey** [comment]
Я вот думаю, нужно ли заморачиваться насчет нелатинских символов в емейле?) Какая вероятность, что они будут использоваться?
