### ISSUE TITLE
Добавить инструкцию по деплою демо

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#197]
### Problem description

Для того чтобы увидеть добавленные функции, необходимо показать демо-версию. Это поможет быстрее проверять PR и получать отзывы о них.

### Proposed solution

Вам необходимо добавить инструкции по развертыванию в README 
Пример можно взять здесь https://ru.hexlet.io/blog/posts/railway

**Comment by AnastasiaKv** [comment]
возьму в работу

**Comment by fey** [comment]
@AnastasiaKv кажется я это покрыл этим ПРом - https://github.com/hexlet-rus/runit/pull/211
Можно его посмотреть и по инструкции оттуда пройти путь по деплою приложения на render.com

**Comment by AnastasiaKv** [comment]
@fey, да вижу.
@acidmaksim , думаю можна закрыть ишью....
