### ISSUE TITLE
Долгая загрузка ассетов

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#207]
Ассеты долго грузятся в первый раз. Необходимо посмотреть, что можно улучшить, чтобы загрузка приложения была быстрее, либо грузилось самое необходимое, а потом остальное
Сейчас это очень заметно для новых пользователей.

![image](https://user-images.githubusercontent.com/697178/219945197-f6824144-960a-46f8-b6d6-3a8a503a78da.png)

**Comment by tysky** [comment]
Хотел бы взять

**Comment by fey** [comment]
@tysky давай)

**Comment by boldurean** [comment]
Вроде проблема решена, может закрыть PR?

**Comment by fey** [comment]
Да, давай
