### ISSUE TITLE
Bug: Ошибка 400 при попытке создания нового сниппета, после удаления сниппета.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-rus/runit#209]
### Summary

После создания сниппета, если вернуться из редактора обратно в профиль и удалить, только что созданный сниппет, новый не создается. В network ошибка 400. Проблема решается перезагрузкой страницы.
![image](https://user-images.githubusercontent.com/102296858/220299169-d79f6361-ad98-46e8-91c5-03a92503df8a.png)

### Reproduction steps

```bash
- Авторизоваться в приложении RunIT.
- Нажать кнопку "Новый сниппет"
- Нажать кнопку "Сохранить"
- Нажать кнопку "Профиль"
- Выбрать "Удалить" в Select сниппета
- Нажать кнопку "Удалить"
- Нажать кнопку "Новый сниппет"
- Нажать кнопку "Сохранить"
```

### Expected result

Создается новый сниппет. 

### Actual result

Новый сниппет не создается. Нажатие на кнопку "Сохранить" выдает ошибку 400.

### Browsers

Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)

**Comment by AleksKostin** [comment]
Беру задачу себе

**Comment by AnastasiaKv** [comment]
@AleksKostin, мне кажеться, этот баг решен, просто проект не задеплоен.

**Comment by AleksKostin** [comment]
> @AleksKostin, мне кажется, этот баг решен, просто проект не задеплоен.

У кого точно узнать решен или нет баг?

**Comment by AnastasiaKv** [comment]
@AleksKostin, запустить последнюю версию проекта локально?
