### ISSUE TITLE
Feature request: Функционал модального окна "Поделиться" в редакторе сниппетов

### ISSUE THREAD

**Issue by 2KO1** [hexlet-rus/runit#210]
### Problem description

При нажатии на кнопку "Поделиться" в редакторе сниппетов появляется модальное окно "Сохраните, чтобы поделиться" в данном окне кнопка "Сохранить сниппет" не работает, при этом по назначению дублирует работающую кнопку "Сохранить"
![image](https://user-images.githubusercontent.com/102296858/220612345-9538e04e-440b-421b-87eb-101907095c1f.png)

### Proposed solution

Возможно имеет смысл привести данное модальное окно к единому виду с модальным окном в главном меню приложения, со вкладками "ссылка", "код для вставки", "сохранить сниппет", но первые две вкладки сделать неактивными до сохранения сниппета.
![image](https://user-images.githubusercontent.com/102296858/220613185-3f6a2ba5-5abe-491b-9193-999238431e85.png)

**Comment by AnastasiaKv** [comment]
@2KO1,  кажеться, данная проблема была решена в только что закрытом issue #169

**Comment by 2KO1** [comment]
@AnastasiaKv т.е. модальное окно при нажатии на кнопку "поделиться" приведено к общей форме? или просто кнопка "сохранить сниппет" работает?

**Comment by AnastasiaKv** [comment]
@2KO1 "общая форма" была изменена, так как таб с сохранением для уже существующего сниппета был не совсем логичным.
![2023-02-24_16-06-52](https://user-images.githubusercontent.com/10958822/221186734-24b91ae3-0ac6-47f3-bcde-a4800d99c83b.png)
При нажатии "поделиться" сейчас открываеться модальное окно (как и при нажатии "новый сниппет" с другим хедером). Сниппет сохраняеться, меняеться роут. Для сохранненых сниппетов шер-кнопки имеют "общую форму"
![2023-02-24_16-08-03](https://user-images.githubusercontent.com/10958822/221186740-0f8b79f5-e5e2-467f-b7da-03403925dd77.png)

**Comment by 2KO1** [comment]
Перепроверил
