### ISSUE TITLE
Bug: Возможность создания сниппетов с одинаковыми названиями.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-rus/runit#212]
### Summary

Существует возможность создания нового сниппета с уже существующим названием, также можно изменить название сниппета на уже существующее.
![image](https://user-images.githubusercontent.com/102296858/221609210-3f70e6e1-09f2-4951-be20-b9fc6b969a02.png)

### Reproduction steps

```bash
- Авторизоваться в приложении RunIT.
- Нажать кнопку "Новый сниппет"
- Нажать кнопку "Сохранить"
- Нажать кнопку "Профиль"
- Нажать кнопку "Новый сниппет"
- Ввести название предыдущего сниппета
- Нажать кнопку "Сохранить"
- Нажать кнопку "Профиль"
```

### Expected result

При попытке ввести существующее название отобразится сообщение об ошибке.

### Actual result

Сниппету с одинаковыми названиями создаются.

### Browsers

Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)

**Comment by AnastasiaKv** [comment]
@2KO1 , этот баг уже тоже не баг)))
[Доказательства...](https://drive.google.com/file/d/1b4Wrs2T3Z9-tHX0UBj5wi-wn9YTQRo28/view)
Было б хорошо задеплоить последнюю версию, только не понимаю к кому обратиться

**Comment by 2KO1** [comment]
@AnastasiaKv ну так создался же сниппет с идентичным названием или я что-то не понимаю?)

**Comment by AnastasiaKv** [comment]
@2KO1, ооо, я не внимательно прочитала описание. Раньше просто название сниппета со слагом было связано, что вызывало много мелких багов.
На счет данного бага, я не думаю что это проблема и нужно выбрасывать ошибку, в [codepen ](https://codepen.io/), например, можно создавать пены с одинаковыми именами, в [replit](https://replit.com/) тоже создается, но индексируется автоматически, типа index b index(1)
Возможно я ошибаюсь...

**Comment by 2KO1** [comment]
@AnastasiaKv индекс был бы выходом, просто если сниппетов 4, то ладно, но если представить наличие 10, то одинаковые названия могут начать вызывать трудности, требований как таковых на это нет, но я думаю наличие индексов и вправду было бы самым оптимальным вариантом

**Comment by 2KO1** [comment]
@AnastasiaKv я бы поменял статус проблемы, если бы умел...=)
