### ISSUE TITLE
New task for MVP

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#22]
- [x] #23

- [x] #24
Slug - is a processed snippet name, which does not contain spaces and is unique among the user's snippets.  It must be saved in DB. 

- [x] #25

- [x] #26

- [x] #27

- [x] #28

- [x] #29

**Comment by fey** [comment]
@ssssank надо проверить, все ли мы из этого сделали для mvp. Может что-то еще не учли.
