### ISSUE TITLE
Не очевидное поведение. Сохранение во время запуска

### ISSUE THREAD

**Issue by Fessan** [hexlet-rus/runit#222]
### Problem description

Для меня, как пользователя, не очевидно что код будет сохранен при запуске программы. https://i.imgur.com/LBK7M2T.png

### Proposed solution

Предлагаю изменить текст https://i.imgur.com/LBK7M2T.png на "Код будет сохранен автоматически при нажатии на кнопку "Запустить"

**Comment by fey** [comment]
Конкурентов можно тут глянуть https://github.com/hexlet-rus/runit/wiki/Other-services-for-coding

**Comment by Fessan** [comment]
> Конкурентов можно тут глянуть https://github.com/hexlet-rus/runit/wiki/Other-services-for-coding

давай я сделаю.
Проведу анализ, распишу варианты.

**Comment by semenChe** [comment]
Я посмотел парочку конкурентов, там подобная надпись вообще не предусмотрена)
Но ведь у нас сохранение происходит автоматически при вводе, а не только после нажатия кнопки "запустить"

**Comment by boldurean** [comment]
Мне нравится как сделано на [stackblitz.com](https://stackblitz.com/)
Есть несколько стадий:

1. не сохранённый (изменённый) код 
<img width="648" alt="idle" src="https://user-images.githubusercontent.com/64642760/229918598-ec36c927-ce30-44b7-9350-b7d506344bd6.png">

2. Если нажать cmd+s/ctrl+s сниппет сохраняется с индикатором
<img width="638" alt="saving" src="https://user-images.githubusercontent.com/64642760/229918650-bac6d525-d605-4a33-ac11-24dcca09b4f2.png">

3. Сохранённый. Выключенная кнопка.
<img width="578" alt="saved" src="https://user-images.githubusercontent.com/64642760/229918674-41466c73-2439-421e-8a39-3157661b9054.png">

**Comment by fey** [comment]
Сниппеты сохраняются во время редактирования кода.
