### ISSUE TITLE
Не корректный текст "Создать бесплатный аккаунт"

### ISSUE THREAD

**Issue by Fessan** [hexlet-rus/runit#223]
### Problem description

"Создать бесплатный аккаунт" - может ввести пользователя  в заблуждение, что есть не только бесплатные аккаунты.

https://i.imgur.com/wwN6WGm.png

### Proposed solution

убрать слово "бесплатный" https://i.imgur.com/wwN6WGm.png

**Comment by antonkrupin** [comment]
беру в работу

**Comment by fey** [comment]
https://github.com/hexlet-rus/runit/pull/227
