### ISSUE TITLE
Feature request: Сделать вход через github, а то регаться лень

### ISSUE THREAD

**Issue by mokevnin** [hexlet-rus/runit#228]
### Problem description

сабж

### Proposed solution

Реализовать вход через Github. 
При первом входе (аккаунта нет) автоматически создается пользователь с рандомным паролем. Если пользователь такой уже есть (по емейлу), то к нему привязывается Github.

Примеры

https://cv.hexlet.io/
https://sicp.hexlet.io/
https://code-basics.com/ru/session/new

![image](https://user-images.githubusercontent.com/697178/229590119-ef65427b-54d5-47ef-b551-66baffda7d9a.png)

![image](https://user-images.githubusercontent.com/697178/229590652-2c1f4c83-c9b1-4b7a-a67a-ef7e87a1e17c.png)

**Comment by dzencot** [comment]
Взял в работу
