### ISSUE TITLE
Describe swagger api

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#235]
### Problem description

В проект добавлена апишка swagger, но там все пусто.
https://runit.hexlet.ru/api
https://github.com/hexlet-rus/runit/issues/235

### Proposed solution

Описать методы апи, дто, чтобы фронтендерам было более проще жить.

**Comment by LarendsD** [comment]
Беру в работу

**Comment by ssssank** [comment]
@fey думаю, можно закрывать

**Comment by fey** [comment]
@ssssank добавишь в ридми ссылку на апи? Тогда ишшус можно будет закрыть :)

**Comment by ssssank** [comment]
@fey добавил: https://github.com/hexlet-rus/runit/commit/c00a9c70b5923b87640107e662da02105e02d76d
