### ISSUE TITLE
update snippets without slug

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#237]
### Problem description

Сейчас в базе неконсистентные данные. Есть сниппеты без слага.

### Proposed solution

Обновить сниппеты, у которых `null` слаги. Лучше всего сделать через миграцию.

**Comment by LarendsD** [comment]
Взял в работу

**Comment by fey** [comment]
@ssssank эта штука еще не доделана.

@LarendsD тут еще чего-то не хватает. Миграция есть, но она не накачена.
![image](https://user-images.githubusercontent.com/697178/235926315-a56b918d-d2a9-48fd-b45f-f3ffc8ddbc32.png)
![image](https://user-images.githubusercontent.com/697178/235926354-19beab5c-874a-4ac2-a239-c1f1fcff6d52.png)

**Comment by LarendsD** [comment]
@fey странно, у себя проверял, создавал сниппеты с null слагом и запускал миграции, заполнялась норм, остались какие-нибудь логи при выполнении миграции? Там вообще UPDATE какой-нибудь писался? Если не осталось, попробую у себя задеплоить и запустить

**Comment by fey** [comment]
@LarendsD а как ты миграцию запускал?) Тут суть в том, что она вообще не накачена.

**Comment by LarendsD** [comment]
@fey блин, подумал что последняя как раз эта, а эта другая, миграцию через make db-migrate запускал

**Comment by LarendsD** [comment]
@fey а точно NODE_ENV=production стоит? Просто эта миграция ставится только при production

**Comment by fey** [comment]
![image](https://user-images.githubusercontent.com/697178/236141345-d7b2dc46-ffab-4e17-9cf3-3e02a504b907.png)

**Comment by LarendsD** [comment]
Странно, попробую у себя задеплоить и посмотреть

**Comment by LarendsD** [comment]
Задеплоил у себя, удалил миграцию с бд и сделал сниппеты со слагом null:
![изображение](https://user-images.githubusercontent.com/84834138/236541430-e7939c05-f2ca-4459-94ec-554ec733e632.png)
![изображение](https://user-images.githubusercontent.com/84834138/236541701-8b432172-7d5d-4a0c-ad4e-6c5743031817.png)
Сделал редеплой и нормально всё прошло;
![изображение](https://user-images.githubusercontent.com/84834138/236542931-22d5ec9e-b86d-47db-819b-d17b5b646c14.png)
![изображение](https://user-images.githubusercontent.com/84834138/236543042-d62595bb-cf78-47fc-9b4b-2e9dd50ba930.png)
![изображение](https://user-images.githubusercontent.com/84834138/236543102-c3f98e57-89ff-40e9-91d2-2f500fa57882.png)
Может дело в количестве обновляемых данных при миграции, хотя наврятли

**Comment by LarendsD** [comment]
Как минимум если миграция выполнилась всё таки, но ни одной новой миграции не нашла, то должно вывести что-то такое:
![изображение](https://user-images.githubusercontent.com/84834138/236551932-c559f6ce-206e-4637-85a0-fcd5d2a8e8f7.png)

**Comment by fey** [comment]
@dzencot можешь глянутЬ? Скорее всего созданные миграции автоматом не применяюстя и их надо прописывать.

**Comment by dzencot** [comment]
Проверил, миграция вроде как есть 
![image](https://github.com/hexlet-rus/runit/assets/3888419/50a8e284-2f03-47bb-a46c-4af43334bf04)

**Comment by fey** [comment]
ага, тоже проверил. Миграция накачена, все сниппеты обновлены :+1:
