### ISSUE TITLE
We need to change the routing of the viewer and the editing of the snippet to this structure https://runit.hexlet.ru/users/{login}/snippets/{slug}

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#24]
Slug - is a processed snippet name, which does not contain spaces and is unique among the user's snippets.  It must be saved in DB.

**Comment by Takaiva** [comment]
Беру!

**Comment by Takaiva** [comment]
Задачка свободна, не хватает времени!

**Comment by antonkrupin** [comment]
Возьму в работу

**Comment by acidmaksim** [comment]
@antonkrupin получается?

**Comment by antonkrupin** [comment]
Освобождаю задачу, времени не хватает

**Comment by vladikKir** [comment]
Если не занята, беру в работу

**Comment by acidmaksim** [comment]
@dzencot сделал эту задачу
