### ISSUE TITLE
Дать возможность гостям пользоваться редактором и сохранять сниппеты

### ISSUE THREAD

**Issue by ssssank** [hexlet-rus/runit#257]
### Problem description

https://runit.hexlet.ru/editor сейчас гость может открыть страницу, но не может писать код

### Proposed solution

Нужно дать возможность гостю редактировать код и делиться ссылкой. Куда-то в сессию (куки) должна сохраняться инфа о пользователе (с защитой, чтобы нельзя было заменить данные в куке), чтобы этот пользователь мог редактировать собственный сниппет

**Comment by Zhar-anna** [comment]
Попробую

**Comment by ssssank** [comment]
@Zhar-anna как успехи? получается что-нибудь? есть вопросы? :)

**Comment by MussonTMN** [comment]
Попробую решить.

**Comment by fey** [comment]
Возможно создавать анонимного юзера с рандомным айдишником (id посетителя). Пользователю вешать куку для идентификации его с этим анонимным юзером, чтобы можно было редактировать свои сниппеты. Если пользователь теряет  куку, то соотеветнно его айди меняется (ну или придумать способ трекать юзеров).
На фронте на лендинг добавить кнопку кодить без регистрации.

**Comment by fey** [comment]
@MussonTMN Привет. Как у вас успехи? что-то получается?

**Comment by Heaven-Tonight** [comment]
Добрый вечер.

Не решили в итоге? Если нет, попробую.

**Comment by Heaven-Tonight** [comment]
Пока исследую код, возник вопрос: мы хотим сохранять гостя в базу данных, например, в отдельный репозиторий с указанием времени, через которое его нужно будет оттуда удалить?

Или нужно подумать, как работать с гостями без сохранения их в БД?

**Comment by fey** [comment]
если сниппет создается, то по-любому нужно его сохранять в бд. Но сохранять ли пользователя? Хороший вопрос.
Вижу здесь несколько вариантов
1) создавать сниппеты, у которых нет пользователя-владельца. Тогда как нам разершить взомжность гостю править свои сниппеты? Нужно брать какой-то идентификатор пользователя. Возможно - айпишник и что-то еще
2) Создавать фейкового пользователя на создание сниппета. Скрыто регистрируем пользователя, создаем ему токен.
Также храним данные о госте, как об обычном бзере. Если он захочет зарегаться, то апдейтим юзера-гостя и присваиваем ему его сниппеты

Мне нравится второй вариант. У нас будут пользователи в разных состояниях типа guest, registered и мы сможем ими управлять :thinking:

**Comment by fey** [comment]
https://onecompiler.com/ - пример сервиса где можно кодить без регистрации

**Comment by Heaven-Tonight** [comment]
Вот у меня тоже была идея как бы псевдорегистрации пользователя.

1. На фронте - вешаем на landing кнопку "кодить без регистрации".

2. При нажатии на кнопку перенаправляем на страницу, где можно добавлять сниппеты:

- если мы уже скрыто зарегили пользователя и его снипппеты еще не очищены, то они загружаются

- если нет, пользователь первый раз кликнул на создание сниппета, то скрыто регистрируем пользователя.

3. Скрытая регистрация - сделать новый rout (например guest) и его обработку на сервере  

  тогда на сервере 

  1. Мы можем расширить модель пользователя, добавив к ней поле status 
  (в таком случае нужно обновить базу данных уже зареганных юзеров - добавить им поле { status: user }.

  2. Добавить логику установки статуса "user" - если идут обращения по роуту регистрации.

  3. Обрабатывая роут guest мы присваиваем статус пользователю guest и возможно пустые поля email и password? Добавляем гостя в репозиторий.

  4. Генерируем и выдаем токен псевдопользователю. 
  
Ставим таймер, например, через 2 часа очистить сниппеты. Пользователя можно предупредить, что через 2 часа данные будут обнулены. По истечении 2 часов очищаем сниппеты пользователя.
  
 5. Пользователь решает зарегаться. Обновляем данные пользователя, меняем статус на user, его сниппеты остаются с пользователем. 
  
Либо как вариант очищать сниппеты при закрытии вкладки, тогда на сервере не используем логику таймера, а очищаем сниппеты конкретного пользователя, но тогда с фронта надо сообщить серверу, что вкладка закрылась, изволь очистить сниппеты. 
  
Также можно добавить логику, что бы через какое-то время можно было бы отследить, что пользователь со статусом guest не был на сайте условно месяц, и тогда удалять его из базы данных зарегистрированных пользователей.

**Comment by fey** [comment]
а давайте не будем делать скрытую регистрацию?
Например сделаем как - на лендинге кнопка "кодить без регистрации" - по ней юзер кликает и мы выполняем запрос с явной регистрацией. Он на нее нажимает, открывается модалка с выбором языка
Дальше сразу создаем юзера типа guest_abcd, логиним его, даем токет аутентификации. 
Да, у нас добавятся пользователи-гости, но при этом мы можем использовать те же роуты, что и везде в принципе. Ну и потом улучшать это дело. Выглядит, что пока на беке нам не придется ничего менять. 

Сниппеты по таймеру думаю не стоит убирать, ведь юзер может поделиться ими. Регитсрация нужна для того, чтобы управлять этими сниппетами удобно.

по сути мы будем создавать сразу юзера, без ввода логина-пароля-емейла. Логин будет давать рандомный (guest_abcd), пароль другой, емейла нет (можно какой-то тоже генерить). У юзера будет стейт типа unregistered/guest
Дальше если юзер хочет регистрации, он может к своему профилю например гитхаб привязать.

**Comment by Heaven-Tonight** [comment]
Вообще да, так, пожалуй, лучше. Возьму?

**Comment by fey** [comment]
да, можете пробовать.
