### ISSUE TITLE
Разделить страницу сниппетов и профиля

### ISSUE THREAD

**Issue by ssssank** [hexlet-rus/runit#258]
### Problem description

Сейчас на одной странице разная информация: данные пользователя, его настройки, а также список сниппетов и добавление нового

### Proposed solution

Разделить страницу на две отдельные: сниппеты и профиль пользователя. Сделать роут вида /users/usernamesnippets - со списком сниппетов. 

Для примера можно посмотреть, как устроено разделение на сервисе codepen

**Comment by fey** [comment]
@M4XPRD пока дизайна нет, давайте ориентироваться на то, что у нас будет сайбар, где будет меню для переключения между разными разделами. 
Примеры:
https://sicp.hexlet.io/settings/account
![image](https://github.com/hexlet-rus/runit/assets/697178/33c10864-4315-40ed-a6ff-52ada5165cf0)
https://cv.hexlet.io/ru/account/profile/edit
![image](https://github.com/hexlet-rus/runit/assets/697178/85ce35c7-c241-4d5e-bc14-37779411fd90)
