### ISSUE TITLE
Bug: При входе через github срабатывает валидация формы

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#266]
### Summary

![image](https://github.com/hexlet-rus/runit/assets/697178/d5e853ed-31b1-4f16-ba68-659ebef52cc5)

Возможно происходит из-за того, что в первое поле устанавливается автофокус. Возможно не стоит выводить в это поле сообщение об ошибке, если там ничего не было введено.

### Reproduction steps

```bash
1. Входим на страницу регистрации или входа, https://runit.hexlet.ru/signup
2. Тыкаем на ссылку "войти через гитхаб"
```

### Expected result

Форма остается чистой без ошибочных сообщений валидации

### Actual result

Поле электронная почта посвечено + сообщение о валидации

### Browsers

Chrome

### OS

Linux

**Comment by NadyKamenskaya** [comment]
Беру в работу!
