### ISSUE TITLE
Bug: невозможно зарегистрироваться через github, если в github нет публичного email

### ISSUE THREAD

**Issue by ssssank** [hexlet-rus/runit#267]
### Summary

Невозможно зарегистрироваться через github, если в github нет публичного email.

### Reproduction steps

```bash
.
```

### Expected result

.

### Actual result

.

**Comment by Mabby20** [comment]
взяли в работу с @peperopuripuri

**Comment by fey** [comment]
Мы перекладываем на на соц сети всю верификацию почтовых ящиков, чтобы самим этим не заниматься. Поэтому кажется будет более правильно требовать от юзера заполнить публичный емейл. (например выводить флеш-сообщение с неудачной попыткой реги).

**Comment by ssssank** [comment]
@AavadaKedavra проверь, пожалуйста, и вот этот баг. Возможно понадобится завести ещё одну учётку на гитхабе для этого теста

**Comment by fey** [comment]
fixed
