### ISSUE TITLE
Сделать новый лендинг

### ISSUE THREAD

**Issue by ssssank** [hexlet-rus/runit#279]
### Problem description

Текущий лендинг неплох, но пришло время его обновить

### Proposed solution

Сверстать и накатить лендинг по макету:
https://www.figma.com/file/Bg2lLcGXG1mpyimERbeqP8/RunIT?type=design

**Comment by SemyonSt** [comment]
Попробую сделать

**Comment by ssssank** [comment]
@SemyonSt как успехи? :)

**Comment by SemyonSt** [comment]
Да не очень :(

**Comment by ssssank** [comment]
Совсем не очень и задачу можно отдать другому или делаешь неспеша?

**Comment by SemyonSt** [comment]
Если есть кандидаты, то пусть берут)
Либо можем поделить и помогать друг другу, а то я застрял

**Comment by ssssank** [comment]
Если ты что-то начал делать, то закидывай это в ПР, путь даже совсем немного, а там уже можно найти кого-нибудь в помощь

**Comment by Sckandinav** [comment]
Привет, я готов взяться)

**Comment by SemyonSt** [comment]
Да, бери)

**Comment by Ledchig** [comment]
@Sckandinav Привет. Готов забрать эту задачу. Ты будешь ее продолжать?

**Comment by Sckandinav** [comment]
привет, да, забирай

**Comment by HelenOne** [comment]
@Ledchig привет! как дела с лендингом нужна помощь?

**Comment by Ledchig** [comment]
@HelenOne нужна помощь. Я основную часть сделал, но мелкие штуки меня выбили. Можем в телеге списаться, я бы задал вопросы.
Telegram: @Ledchig

**Comment by fey** [comment]
@Ledchig привет, можешь накидать немного сюда, что пошло как надо, а что нет?)
Думаю, что другим ребятам будет полезно и интересно узнать, и вероятно что-то смогут подхватить в работу.

**Comment by HelenOne** [comment]
@fey мы договорились созвониться с @Ledchig и обсудить, но в целом, да, если удастся описать письменно, может и без созвона сможем направить/подключить кого-нибудь в помощь)

**Comment by fey** [comment]
кул! давайте только не тет-а-тет, а если есть возможность - позвать желающих поспрашивать ,посмотреть, позадавать вопросики =)

**Comment by Ledchig** [comment]
Для себя вчера вечером накидал такие задачи:
- анимации при наведении на элементы меню и кнопки
- ссылки проставить
- фоновые картинки
- карусель заменить на инлайн блок со скролом?
- черный фон для трех фигур в ряд после первой кнопки "начать кодить"
- цвета для тем
- как обработать "Напишите нам"?

Из них у меня не получается с фоновыми картинками совсем никак. Читал доку, смотрел примеры, еле как сделал первую картинку похожей процентов на 80 от образца, но не то.
Ну и как обрабатывать "Напишите нам" в подвале не очень понимаю. Просто по submit'у отправлять на какую-то почту сообщение?
С остальным, кажется, что смогу справится.

**Comment by HelenOne** [comment]
@Ledchig а где код пишешь?

**Comment by HelenOne** [comment]
@Ledchig думаю можно пока не делать фоновые картинки, а "Напишите нам" нужно обрабатывать так, как сейчас уже сделано
Там по идее даже не нужно логику менять в этом месте, только стили

Не забывай мержить себе изменения из main периодически

**Comment by Ledchig** [comment]
Потихоньку возвращаюсь к работе. Сейчас эффекты пытаюсь при наведении сделать, с ссылками легко получилось, а кнопки пока не получаются

**Comment by Ledchig** [comment]
Потихоньку возвращаюсь к работе. Сейчас эффекты при наведении сделал.

**Comment by Ledchig** [comment]
Я добавил фоновые картинки. Из-за контейнеров с ограничинной шириной при разрешении 1920х1080 выглядит более менее, но если оно больше, то все плохо. Как лучше поступить? Сделать fluid контейнер что бы по всему экрану тянулся или пытаться подстроиться под контейнеры на брэйкпоинтах?
@fey @HelenOne

**Comment by fey** [comment]
по идее у нас дефолтный бутстрап. Нужно посмотреть, как он с этим справится. Картинки можно например спрятать и не показывать их, если с ними все плохо

**Comment by Ledchig** [comment]
https://ledchig-runit.onrender.com/ - посмотрите в темном режиме. Как лучше поступить?

**Comment by geophyzik** [comment]
небольшой фидбек 
<img src="https://github.com/hexlet-rus/runit/assets/115660566/9cd2000a-614d-4461-8e15-1c1288343b5d" width="400" height="200" />
при просмотре сайта с тачпада этот элемент цепляется и не дает нормально скроллить страницу

**Comment by Ledchig** [comment]
@geophyzik 
Сейчас лучше? Это на маке так было?

**Comment by geophyzik** [comment]
> @geophyzik
> Сейчас лучше? Это на маке так было?

неа
да на маке, но эт не важно, на любом ноуте с похожим разрешением ты при скролле тачпадом дойдешь до этого элемента и если курсор окажется на нем скроллиться будет уже сам элемент, прост в плане ux дизайна наверн эт такое себе решение
ниже скрин того как при дефолтном масштабе эт выглядит
<img width="1421" alt="Снимок экрана 2023-12-15 в 23 07 58" src="https://github.com/hexlet-rus/runit/assets/115660566/c1d25860-3d8d-4bdf-8f76-487d2cbbf8ad">
