### ISSUE TITLE
Bug: Ссылка на вкладку профиль не работает

### ISSUE THREAD

**Issue by AavadaKedavra** [hexlet-rus/runit#282]
### Summary

Не работает ссылка https://runit.hexlet.ru/profile

### Reproduction steps

```bash
1. Перейти по ссылке https://runit.hexlet.ru/profile

Проверено на https://hexlet.testops.cloud/project/1/defects/101
```

### Expected result

Авторизованный пользователь перенаправлен на вкладку профиля.
Неавторизованный пользователь перенаправлен на страницу авторизации

### Actual result

Не работает ссылка https://runit.hexlet.ru/profile отображается ошибка страницы "404"
![bug1](https://github.com/hexlet-rus/runit/assets/126116401/08d9f6c9-d9fd-40cd-bdd4-ebe282673290)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by IgorLebedev** [comment]
по нажатию на кнопку профиль в навбаре, перекидывает на https://runit.hexlet.ru/profile/snippets, там по сути так и должно отрабатывать как мне кажется

**Comment by AavadaKedavra** [comment]
@IgorLebedev  проблема еще в том, что этот баг завязан с #283 при авторизации через гит перенаправляет по этой ссылке

**Comment by peperopuripuri** [comment]
взяли в работу с @Mabby20

**Comment by AavadaKedavra** [comment]
Работает.
