### ISSUE TITLE
Bug: Невозможно авторизоваться через Github, "statusCode":500

### ISSUE THREAD

**Issue by AavadaKedavra** [hexlet-rus/runit#283]
### Summary

Запрос на авторизацию через Github обрабатывается неверно, перенаправлен на страницу с ошибкой 500.

Проверено на https://hexlet.testops.cloud/project/1/defects/103

### Reproduction steps

```bash
1. Открыть https://runit.hexlet.ru/login
2. Нажать кнопку "Войти с помощью: GitHub" 
3. При необходимости ввести данные для авторизации в Github
```

### Expected result

Пользователь авторизован, выведено сообщение "Вход в систему выполнен через учетную записью Github."

### Actual result

Авторизации в Runit не происходит, перенаправлен на страницу с ошибкой "500"
![bug2](https://github.com/hexlet-rus/runit/assets/126116401/f00aca37-2d00-4943-a343-0c44e1372d43)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by fey** [comment]
@AavadaKedavra а публичный емейл есть? https://github.com/settings/profile
![image](https://github.com/hexlet-rus/runit/assets/697178/86ca9293-6905-42a8-a82c-3b41cfd52438)

**Comment by AavadaKedavra** [comment]
@fey Нет, публичного нет

**Comment by AavadaKedavra** [comment]
Получилось зайти после добавления публичного email в Github. 
Однако сначала перенаправляет на https://runit.hexlet.ru/profile #282 
![image](https://github.com/hexlet-rus/runit/assets/126116401/409def77-1894-4456-bfae-8bf44c52ec6e)
Лечится с помощью нажатия на "профиль" или лого сайта

**Comment by AavadaKedavra** [comment]
Возможно нужно прикрутить какое-нибудь требование/предупреждение  "для авторизации через GIthub необходим публичный email" И поправить/заменить неработающую ссылку

**Comment by Mabby20** [comment]
взяли в работу с @peperopuripuri

**Comment by faciledictu** [comment]
Можно предложить ввести e-mail для продолжения регистрации, если его нельзя получить из гитхаба. Я где-то видел такой сценарий

**Comment by fey** [comment]
Мы перекладываем на на соц сети всю верификацию почтовых ящиков, чтобы самим этим не заниматься. Поэтому кажется будет более правильно требовать от юзера заполнить публичный емейл. (например выводить флеш-сообщение с неудачной попыткой реги).

**Comment by AavadaKedavra** [comment]
Работает.
