### ISSUE TITLE
Bug: Не отображается предупреждение о неуспешной регистрации, при попытке повторно зарегистрироваться по email

### ISSUE THREAD

**Issue by AavadaKedavra** [hexlet-rus/runit#284]
### Summary

Проверено на https://hexlet.testops.cloud/project/1/dashboards

### Reproduction steps

```bash
1. Открыть https://runit.hexlet.ru/signup
2. Ввести уже зарегистрированный email "Ivanov22@mail.ru"
3. Ввести корректный логин
4. Ввести и продублировать корректный пароль
5. Нажать "Регистрация"
```

### Expected result

Регистрация не происходит, отображается предупреждение о неуспешной регистрации "Данный email уже используется"

### Actual result

Регистрация не происходит, но предупреждение о неуспешной регистрации не отображается
![bug4](https://github.com/hexlet-rus/runit/assets/126116401/64d446a8-dbd7-4582-a076-8fd55da5e53e)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by MussonTMN** [comment]
возьму в работу

**Comment by Aallyycoop** [comment]
Возьму в работу

**Comment by faciledictu** [comment]
Я возьму это в работу. Он косвенно связан с https://github.com/hexlet-rus/runit/issues/285

**Comment by faciledictu** [comment]
Ишью исправлен вместе с https://github.com/hexlet-rus/runit/issues/285 Можно закрывать
