### ISSUE TITLE
Bug: Некорректно отображается предупреждение, при попытке регистрации по уже занятому логину 

### ISSUE THREAD

**Issue by AavadaKedavra** [hexlet-rus/runit#285]
### Summary

**Precondition:** аккаунт с логином Ivanov22 - уже зарегистрирован
Должны подсвечиваться только, неправильно заполненные поля
_Проверено на https://hexlet.testops.cloud/project/1/dashboards_

### Reproduction steps

```bash
1. Открыть https://runit.hexlet.ru/signup
2. Ввести корректный email
3. Ввести занятый логин "Ivanov22"
4. Ввести корректный пароль
5. Продублировать пароль в поле подтвердить пароль
6. Нажать "Регистрация"
```

### Expected result

Подсвечивается красным, только поле с  занятым логином.

### Actual result

Предупреждение отображается не корректно. Все поля подсвечиваются красным, при попытке зарегистрироваться с занятым логином. 
![bug5](https://github.com/hexlet-rus/runit/assets/126116401/31cf7903-77da-40bd-8ddc-53cdfdb5b039)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by faciledictu** [comment]
Возьму в работу

**Comment by faciledictu** [comment]
Исправлен в https://github.com/hexlet-rus/runit/pull/290 Я не указал ишью в ПР. Ишью можно закрыть
