### ISSUE TITLE
Фронтенд: вынести схемы валидации в отдельные функции для переиспользования

### ISSUE THREAD

**Issue by faciledictu** [hexlet-rus/runit#289]
### Problem description

1. На фронетенде в полях ввода используется валидация средствами yup. При этом схемы валидации прописаны в прямо файлах с компонентами форм. Однако такие поля как `login`, `email`, `password`, `confirmPassword` и `name` (название сниппета) встречаются в разных формах, но требуют одинаковой валидации.
2. В этих схемах также используются сообщения об ошибках валидации. Сейчас некоторые сообщения в модуле локализации дублируются. Например, `signIn.validation.correctEmail` и `signUp.validation.correctEmail`. 

### Proposed solution

1. Я предлагаю вынести схемы валидации для каждого поля в отдельный модуль и импортировать их в компоненты с формами. Так при изменении требований, например, к логину, нужно будет править только один файл.
2. Поправить файлы локалей. Сообщения об ошибках стоит вынести, например, в `errors.validation.<…>` (наряду с основными ошибками) плюс валидатор должен передавать формику не локализованное сообщение, а ключ (то есть в `formik.errors.email` будет лежать _’errors.validation.correctEmail'_). Вытаскивать с помощью i18n локализованное сообщение (`t(formik.errors.email)` >> _'Некорректная электронная почта’_) по этому ключу должен компонент.

**Comment by ilya-rodin** [comment]
Беру

**Comment by faciledictu** [comment]
@ilya-rodin Привет! Смотри, там работы совсем немного. Я набросал файлик с validation schemas, можем скооперироваться. Тебе нужно будет сделать импорт схем из этого файлика во все файлы с компонентами и обновить там код. И обновить сообщения об ошибках в локалях. Если форкнешь, скажи. Я тебе сделаю ПР с этим файлом
