### ISSUE TITLE
Объединить код форм регистрации и логина

### ISSUE THREAD

**Issue by faciledictu** [hexlet-rus/runit#296]
### Problem description

Сейчас логиниться и регистрироваться можно:
1. С соответствующих страниц: `/login` и `/signup`
2. В модальном окне, которое открывается из интереса просмотра сниппета незарегистрированным пользователем

**Итого имеется по два файла, дублирующие функционал:**

`frontend/src/Pages/SignUp.jsx`
`frontend/src/components/Modals/SignUn.jsx`

`frontend/src/Pages/SignIn.jsx`
`frontend/src/components/Modals/SignIn.jsx`

**Обратите внимание, что в каталоге `frontend/src/Pages` код более актуальный, там исправлены баги сообщениями об ошибках логина и регистрации.**

Нужно привести код в модалках в актуальное состояние и вообще устранить дублирование

### Proposed solution

Возможно, код форм стоит вынести в отдельные компоненты и импортировать его в компоненты модалок и страниц соответственно.

**Comment by likurg42** [comment]
Попробую реализовать

**Comment by faciledictu** [comment]
@likurg42 Лучше немного подождать и начать после того, как примут #295
Там изменения как раз в этих файлах

**Comment by likurg42** [comment]
А без проблем, начну когда примут pull request

**Comment by ssssank** [comment]
@likurg42 там ПР приняли, вы не начинали ещё ничего делать?
