### ISSUE TITLE
Добавить спиннер, который должен будет появляться при загрузке страницы

### ISSUE THREAD

**Issue by ilya-rodin** [hexlet-rus/runit#309]
### Problem description

При загрузке страниц приложения со слабым интернетом, показывается просто надпись Loading, что выглядит не очень. Есть предложение добавить спиннер или как-либо еще кастомизировать сообщение о загрузке страницы

<img width="1470" alt="Screenshot 2023-07-12 at 8 03 21 PM" src="https://github.com/hexlet-rus/runit/assets/85010136/45704220-1d69-4008-8e55-597bd374cd62">

### Proposed solution

Найти / написать svg спиннер и добавить его вместо текста Loading при загрузке страницы

**Comment by Aallyycoop** [comment]
Возьму в работу

**Comment by boldurean** [comment]
Там вроде редизайнят сайт полностью так что пока можно не торопиться)

**Comment by SkyAjax** [comment]
Добавил темный фон, чтобы при загрузке не моргало белым цветом и исправил рендер текстов через локаль, а не напрямую в верстке
