### ISSUE TITLE
Не отображается предупреждение о занятом email, если данный email содержит символы в верхнем регистре и уже зарегистрирован

### ISSUE THREAD

**Issue by AavadaKedavra** [hexlet-rus/runit#310]
### Summary

Данный баг справедлив также, если намерено изменить (ошибочно написать) любой из символов в верхнем регистре в уже зарегистрированном email
Пример:
зарегистрированный email: amadacevra@gmail.com - записываем Amadacevra@gmail.com или amAdacevra@gmail.com и т.д.
Баг воспроизводится, условия - запись символа с заглавной буквы.

_Протестировано в Allure TestOps_

### Reproduction steps

```bash
1. Открыть https://runit.hexlet.ru/signup
2. Ввести email Test24@mail.ru
3. Ввести логин test245
4. Ввести пароль test2456
5. Продублировать пароль
6. Нажать "зарегистрироваться"
7. Ввести email tEst24@mail.ru
```

### Expected result

Регистрация не происходит, отображается предупреждение "данный email уже используется"

### Actual result

Регистрация не происходит, но предупреждение при данных условиях не отображается.
![image](https://github.com/hexlet-rus/runit/assets/126116401/18b4cd36-da1e-40f2-a2db-36f22501b2ec)
![image](https://github.com/hexlet-rus/runit/assets/126116401/2cdcf861-dcfd-4d10-bc9d-1ccc808c2e80)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by likurg42** [comment]
Возьму в работу

**Comment by AavadaKedavra** [comment]
баг устранен.
