### ISSUE TITLE
Гипертекст "Карьера в Хекслете" ведет на устаревшую ссылку 

### ISSUE THREAD

**Issue by AavadaKedavra** [hexlet-rus/runit#313]
### Summary

Необходимо уточнить и обновить ссылку на предлагаемую: https://hexlet-ru.notion.site/c6406ed8890747e690d32b050faf42c2
![bug 27](https://github.com/hexlet-rus/runit/assets/126116401/8464925f-703f-496c-bb64-79ff9b8e4ff4)

### Reproduction steps

```bash
1. Открыть https://runit.hexlet.ru/
2. Нажать "Карьера в Хекслете"
```

### Expected result

Перенаправлены на актуальную страницу "С вакансиями Хекслета"

### Actual result

Открывается: https://www.notion.so/c6406ed8890747e690d32b050faf42c2
![image](https://github.com/hexlet-rus/runit/assets/126116401/3b04ebe0-dae0-4bdb-92db-f5302ccc47ca)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by ilya-rodin** [comment]
беру

**Comment by AavadaKedavra** [comment]
Работает! закрываю.
