### ISSUE TITLE
Нарушение верстки при создании +20 сниппетов 

### ISSUE THREAD

**Issue by AavadaKedavra** [hexlet-rus/runit#314]
### Summary

Также верстка ломается при увеличении масштаба страницы с меньшим количеством сниппетов
Возможно нужна пагинация или окно с ползунком для большого количества сниппетов
_масштаб 125%_
![image](https://github.com/hexlet-rus/runit/assets/126116401/4c7f03af-f3a2-4964-8140-c523f589668b)
_протестировано на Allure TestOps_

### Reproduction steps

```bash
1. Открыть https://runit.hexlet.ru/profile/snippets
2. Нажать "новый сниппет"
3. Подтвердить предложенное имя
4. Нажать "профиль"
5. Повторять цикл steps: 2,3,4 до достижения более 20 сниппетов
```

### Expected result

Блок со списком сниппетов отображается корректно, верстка не нарушается

### Actual result

При создании большого количества сниппетов (+20), верстка нарушается, сниппеты "выходят" за рамки блока

_масштаб 100%_
![image](https://github.com/hexlet-rus/runit/assets/126116401/642172d6-ddf8-4c0a-8552-d44d398f83a4)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by likurg42** [comment]
Возьму в работу

**Comment by faciledictu** [comment]
Особого смысла брать нет сейчас это в работу. Я делаю новый дизайн всего приложения. Исправлю в рамках этого.

**Comment by boldurean** [comment]
> Особого смысла брать нет сейчас это в работу. Я делаю новый дизайн всего приложения. Исправлю в рамках этого.

Наконец-то кто-то переделает этот ужасный дизайн)

**Comment by faciledictu** [comment]
#338 закрывает этот ишью

**Comment by vladimirart2811** [comment]
Баг не воспроизводится. 

Browsers: Safari Версия 16.6 (18615.3.12.11.2)/Chrome Версия 116.0.5845.96 (Официальная сборка), (arm64)/Firefox 116.0.3 (64-разрядный)

macOS 13.5 Ventura
