### ISSUE TITLE
Bug: Форма входа не проверяет, заполнено ли поле пароля

### ISSUE THREAD

**Issue by faciledictu** [hexlet-rus/runit#319]
### Summary

При попытке войти в систему без ввода пароля сообщение об ошибке выводится уже после отправки данных на сервер. Мне кажется, лучше было бы уведомить пользователя о необходимости заполнить пароль

### Reproduction steps

Необходимые условия: не быть залогиненным.
1. Нажмите кнопку «Войти» на панели навигации
2. Ввести валидный email в поле Электронная почта
3. Поле для ввода пароля оставить пустым
4. Нажать кнопку «Войти» внизу формы

Prerequisites: do not be logged in.
1. Press Войти button on the navbar
2. Fill in the valid email in the email field
3. Leave the password field empty
4. Press Войти button under the form

### Expected result

Форма должна отобразить сообщение о необходимости ввода пароля. Приложение не должно отправлять запрос, пока пользователь не заполнит оба поля.

The form should display a message about password is required. The app shouldn’t send the request until user fill out both fields.

### Actual result

Приложение пытается войти в систему, посылая запрос на сервер. Сервер возвращает ответ 401 Unautorized

The app trying to sign in, sending request to server. Server returns 401 Unauthorized response

**Comment by TemaGolovin** [comment]
Беру в работу

**Comment by vladimirart2811** [comment]
Баг не воспроизводится. 
Форма отображает сообщение о необходимости ввода пароля. Отправка запроса не происходит. 

Browsers: Safari Версия 16.6 (18615.3.12.11.2)/Google Chrome Версия 115.0.5790.170 (Официальная сборка), (arm64)/Firefox 115.0.3 (64-разрядный)

macOS Ventura 13.5
