### ISSUE TITLE
Feature request: дублирование сниппета

### ISSUE THREAD

**Issue by faciledictu** [hexlet-rus/runit#327]
### Problem description

Сейчас нет возможности дублировать сниппет. Ни из своей коллекции, ни тот, которым поделились.

### Proposed solution

Добавить Возможность форка сниппета, которым с тобой поделились. Две задачи, которые лучше реализовать последовательно.
1. В запросе на создание нового сниппета на сервер должно быть можно посылать его начальный текст.
2. После этого на клиенте добавить реализацию этого функционала.

**Comment by faciledictu** [comment]
Оказывается на сервере это сделано. Клиент возьму сам в работу :)

**Comment by Lena05k** [comment]
Беру

**Comment by faciledictu** [comment]
Сервер при создании нового сниппета принимает в том числе код. Если хотите покопаться на баке, то это где-то тут `backend/src/snippets/snippets.service.ts`
В принципе, это не так важно, как оно реализовано на бэке. Если развернуть приложение в development (то есть локально), то есть удобный способ посмотреть апи по адресу https://localhost:5001/api

**Comment by Lena05k** [comment]
Я правильно понимаю, что нужно добавить функционал, который позволить пользователю форкнуть сниппет? То есть, после нажатия на кнопку “Дублировать”, должен ли появляться модал или сразу дублироваться?

**Comment by Lena05k** [comment]
Ок, было бы здорово закрепить [ссылку на макет (figma)](https://www.figma.com/file/DVkW8by0bPZXxMlEVzO3uz/Hexlet-RunIT?type=design&node-id=46-1606&mode=design) в файле readme.

**Comment by Lena05k** [comment]
> Ок, было бы здорово закрепить [ссылку на макет (figma)](https://www.figma.com/file/DVkW8by0bPZXxMlEVzO3uz/Hexlet-RunIT?type=design&node-id=46-1606&mode=design) в 
 readme.

**Comment by Lena05k** [comment]
Ок, было бы здорово закрепить [ссылку на макет (figma)](https://www.figma.com/file/DVkW8by0bPZXxMlEVzO3uz/Hexlet-RunIT?type=design&node-id=46-1606&mode=design) в readme.

**Comment by fey** [comment]
https://github.com/hexlet-rus/runit/wiki пока сюда закиул.

**Comment by faciledictu** [comment]
Ух… Модалки там не все, кое-что не нарисовано. Например, для дублирования там модалки нет. Это значит, надо мне поддерживать дизайн в актуальном состоянии)

**Comment by fey** [comment]
А зачем нам дизайн модалки нужен? :thinking: 
Давайте какую-нибудь стандартную, на бутрапе. С подтверждением. 
Можно подтверждение даже сделать не через модалку, а через интерфейс браузера (алерт)

**Comment by Lena05k** [comment]
У меня не получается реализовать так, чтобы сниппет дублировался, и я не знаю, как это сделать. Я добавила модалку после нажатия на кнопку "дублировать". Запустить pull request?

**Comment by faciledictu** [comment]
@Lena05k А как пробовали реализовать?
Смотрите, у нас есть процесс создания сниппета. Он вот тут реализован на фронтенде.
https://github.com/hexlet-rus/runit/blob/167dfe6d370997b22ed59776808df401461f5b44/frontend/src/pages/profile/NewSnippetForm.jsx#L35-L53

Вот такой процесс идет в этом случае:
1. Мы берем шаблонный код и записываем его в переменную code (строка 35)
2. Генерируем имя сниппета (38-39)
3. Отправляем запрос на сервер на создание сниппета и именем и кодом (40). Сервер возвращает id.
4. По возвращенному id получаем от сервера параметры сниппета (41)
5. Генерируем ссылку (42) и перебрасываем пользователя на этот сниппет (44).

По сути дублирование — это такое же создание нового сниппета, мы должны дать ему имя, а код взять от уже существующего сниппета.

Пройдитесь по этому алгоритму, какие шаги непонятны или вызывают сложности?

**Comment by Lena05k** [comment]
Хорошо, попробую.

**Comment by Lena05k** [comment]
@faciledictu Как очистить children в SnippetCardWrapper? У меня получилось создать дублирование сниппета без кода. Таким образом, при реализации копирования кода, случайно попала в бесконечный цикл с дублированием.

**Comment by Lena05k** [comment]
С завтрашнего дня я не смогу доделать задание, отказываюсь.

**Comment by likurg42** [comment]
Попробую сделать

**Comment by fey** [comment]
@likurg42 Как у вас успехи? Нужна помощь?
