### ISSUE TITLE
Сделать именование переменных и полей с именем пользователя единообразным

### ISSUE THREAD

**Issue by faciledictu** [hexlet-rus/runit#328]
### Problem description

На сервере сейчас везде login, на клиенте кое-где username, кое-где login. Фактически это не логин (логином является почта).

### Proposed solution

Предлагаю навести порядок и привести наименования к одному варианту. Можно сделать сначала на бэкенде отдельным ПР. Фронтенд могу взять на себя

**Comment by faciledictu** [comment]
Да, кстати, для бэкенда нужно также поменять поле в БД и выполнить миграцию, чтобы не потерять данные, если я правильно понимаю

**Comment by JS-NinjaNN** [comment]
Возьмусь.

**Comment by faciledictu** [comment]
Я возьму
