### ISSUE TITLE
Bug: возможно завершить регистрацию с уже занятым именем пользователя, набранным в другом регистре

### ISSUE THREAD

**Issue by faciledictu** [hexlet-rus/runit#348]
### Summary

App allow to complete sing up with an already taken username entered in a different case

Необходимо, чтобы сервер возвращал ответ с ошибкой, если при регистрации используется уже занятое имя пользователя, независимо от регистра.

При этом регистрироваться можно, используя любой регистр, и сохраняться в бд юзернейм должен в том виде, в котором его вводит пользователь. Вероятно, не стоит приводить все к нижнему регистру?

### Reproduction steps

```bash
1. Зарегистрироваться, используя имя пользователя в нижнем регистре (username)
2. Попробовать зарегистрироваться еще раз, используя имя, отличающиеся только регистром (Username)

1. Sing Up with a username in lowercase (e.g. ‘username’)
2. Try to sign up again with the same username, but in a different letter case (e.g. ‘Username’)
```

### Expected result

Форма регистрации сообщает, что имя пользователя уже занято.

The Sing Up form displays that the username is already taken.

### Actual result

Регистрация проходит успешно, пользователь создан

Registration is successful, the second user has been created

**Comment by DieWerkself** [comment]
Возьму.

**Comment by vladimirart2811** [comment]
Баг не воспроизводится. 

Browser: Safari Версия 16.6 (18615.3.12.11.2)/Google Chrome Версия 115.0.5790.170 (Официальная сборка), (arm64)/Firefox 115.0.3 (64-разрядный)

macOS Ventura 13.5
