### ISSUE TITLE
Добавить форму обновления пароля и метод обновления пароля на бэке

### ISSUE THREAD

**Issue by dzencot** [hexlet-rus/runit#355]
### Problem description

Отдельной формы обновления пароля (если забыл пароль) сейчас нет. Нужно добавить новую, которая будет открываться по ссылке из письма.

### Proposed solution

- Добавить форму с вводом пароля и подтверждением пароля. Форма должна открываться по ссылке типа /recovery/{hash}. Форма должна отсылать пост-запрос с новым паролем на адрес вида /api/users/recover/{hash}
- Переделать роут на беке /api/users/recover/{hash}, чтобы он проверял хеш на корректность. Если хеш актуальный, то обновляем пароль, если нет, то выкидываем ошибку

**Comment by SkyAjax** [comment]
Давайте, я попробую сделать
