### ISSUE TITLE
Bug: Криво работает логин через Github на локальном окружении

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#360]
### Summary

При попытке залогиниться, после редиректа с гитхаба падает с ошибкой на странице http://localhost:5001/profile

### Reproduction steps

```bash
1. Разворачиваем новый проект
2. Делаем `make setup`
3. копируем `backend/.env.example -> backend/.env` чтобы были переменные окружения для локальной разработки
4. `make start` для старта приложения
5. Логинимся http://localhost:3000/signin через Github
6. Подтверждаем, если требуется. 
7. Получаем ошибку
```

### Expected result

Пользователь залогинился, видит страницу с созданием сниппета

### Actual result

```
{"statusCode":404,"message":"ENOENT: no such file or directory, stat '/home/feycot/projects/runit/frontend/build/index.html'"}
```

Текущая страница http://localhost:5001/profile

### Browsers

Chrome

### OS

Linux

**Comment by dzencot** [comment]
В ридми еще есть Configuring authorization via GitHub. Все сделал, что указано?

**Comment by fey** [comment]
Настроил https://github.com/organizations/hexlet-rus/settings/apps/runit-local-use-only 
И там тоже редиректит на 5001 и падает.

**Comment by fey** [comment]
кажется нашел в чем дело. Попробую поправить.
