### ISSUE TITLE
Не работает светлая тема

### ISSUE THREAD

**Issue by glazovanastasia** [hexlet-rus/runit#365]
### Summary

На главной странице невозможно поменять тёмную тему на светлую

### Reproduction steps

```bash
- Открыть https://runit.hexlet.ru/
- В правом верхнем углу выбрать смену яркости темы сайта
- Перейти на светлую тему
```

### Expected result

Яркость главной страницы сайта меняется на светлую тему, цвет текста адаптируется

### Actual result

При переходе с тёмной темы на светлую яркость фона не меняется, часть текста в разделе FAQ становится прозрачным

![image](https://github.com/hexlet-rus/runit/assets/127899807/7b0bd048-1b48-43a9-b0c6-96f4b310323b)

![image](https://github.com/hexlet-rus/runit/assets/127899807/23bbdd1c-73d5-408c-a421-435fdacb467a)

### Browsers

Chrome Версия 116.0.5845.140 (Официальная сборка), (64 бит)

### OS

Windows 11 Pro

**Comment by IrinaKurb** [comment]
Привет. Хочу взяться за задачку
