### ISSUE TITLE
Перевод информации с реквизитами

### ISSUE THREAD

**Issue by glazovanastasia** [hexlet-rus/runit#374]
### Summary

При смене языка сайта в футере меняется информация реквизитов в первом блоке

### Reproduction steps

```bash
1. Выбрать язык сайта английский
2. Проскроллить до футера
3. В первом блоке в строке ОГРН в переводе с русского на английский появляется ИНН на русском языке
```

### Expected result

PSRN 1217300010476

### Actual result

ИНН 7325174845

![image](https://github.com/hexlet-rus/runit/assets/127899807/7480602a-cb33-4a5e-88f9-2c008894af41)

### Browsers

Chrome

### OS

Windows

**Comment by elenashcherbinina** [comment]
возьму в работу

**Comment by elenashcherbinina** [comment]
Или этот баг уже решен? Я просто не вижу лишний ИНН

![Снимок экрана 2023-10-10 в 13 44 05](https://github.com/hexlet-rus/runit/assets/108113888/b1203d89-eeb8-40e3-8df5-960016586efe)

**Comment by HelenOne** [comment]
@elenashcherbinina да, баг потерял актуальность

**Comment by glazovanastasia** [comment]
Но баг остался. Почему он потерял актуальность?
![image](https://github.com/hexlet-rus/runit/assets/127899807/770bd821-40a0-4296-ba1d-4c621b5d7cb8)
![image](https://github.com/hexlet-rus/runit/assets/127899807/8f7bb7d5-f430-48d9-8cef-c1992d864efd)

**Comment by fey** [comment]
@glazovanastasia подскажите, на какой странице смотрите? Возможно еще, что на тот момент не задеплоили новую версию. Сейчас у меня выглядит так 
![image](https://github.com/hexlet-rus/runit/assets/697178/3992eb4c-d8b9-4133-b128-8ab06f9ce035)

**Comment by glazovanastasia** [comment]
@fey на любой странице. Только что ещё раз перепроверила. Из-за сломанного режима светлой темы (ишью #365 до сих пор не взят в работу) получается так, что эта информация не подсвечена, но если выделить курсором левый блок, то всё будет видно. Ну и, соответственно, на ru и en локали разная информация, с чего и стартовал этот ишью

**Comment by fey** [comment]
да, точно. И еще текст есть непереведенный 
![image](https://github.com/hexlet-rus/runit/assets/697178/d6ad0523-2248-4271-b0e6-e84f75b333c1)

**Comment by elenashcherbinina** [comment]
Возьму в работу. 
Вопрос для уточнения: вы хотите, чтобы адрес тоже высвечивался при темной теме, верно?

**Comment by fey** [comment]
Да, текст должен выводиться. Там вроде бы и на светлой и на темной теме темный фон в футере.

**Comment by elenashcherbinina** [comment]
пофиксила невидимость адреса. Класс text-muted почему не виден на bg-dark,скорее всего связано с контрастностью. Заменила на text-secondary. 

Бросилось в глаза, что на старновой странице после faq, тоже есть невидимый абзац, скорее всего связано с тем же. Скриншот прилагаю. Если нужно, дайте знать, исправлю и там.
<img width="1021" alt="Снимок экрана 2023-10-23 в 12 02 48" src="https://github.com/hexlet-rus/runit/assets/108113888/8b299d60-b830-4124-bfa1-28a0714363b4">

**Comment by fey** [comment]
да, там тоже стоит поправит.

**Comment by elenashcherbinina** [comment]
> да, точно. И еще текст есть непереведенный ![image](https://user-images.githubusercontent.com/697178/275545693-d6ad0523-2248-4271-b0e6-e84f75b333c1.png)

Сейчас установлено так, если язык русский, то видим это лицензионное соглашение. Если переключаем  язык, то данной ссылки нет. Так и задумано? 

Еще в русской версии текст лицензионного соглашения открывается в этом же окне.

русский язык
<img width="504" alt="ru" src="https://github.com/hexlet-rus/runit/assets/108113888/3422302b-7b7e-4d76-8059-292045234950">

английский язык
<img width="449" alt="en" src="https://github.com/hexlet-rus/runit/assets/108113888/7b6765cd-1ad2-4be9-baf5-725d6be7ea29">

**Comment by fey** [comment]
да, лиц соглашение пока только для ру локали.

**Comment by fey** [comment]
Да, давайте.
