### ISSUE TITLE
Нет перевода в информации документов

### ISSUE THREAD

**Issue by glazovanastasia** [hexlet-rus/runit#375]
### Summary

В футере во втором блоке с документацией нет перевода лицензионного соглашения

### Reproduction steps

```bash
1. Выбрать язык сайта английский
2. Проскроллить до футера
3. Во втором блоке в строке со ссылкой "Лицензионное соглашение для некоммерческого использования" отсутствует перевод на английский язык
```

### Expected result

Корректный перевод на английский язык с активной ссылкой на лицензионное соглашение

### Actual result

[footer.licenseAgreement](https://runit.hexlet.ru/licenseAgreement)
![image](https://github.com/hexlet-rus/runit/assets/127899807/741eb1cc-6a28-4021-8f5d-0dcbdacf2b1e)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
Давайте для en локали скроем, тк пока нет перевода лицензионного соглашения.

**Comment by Shamatarev** [comment]
готов взять задачу

**Comment by fey** [comment]
@Shamatarev да, давайте.

**Comment by fey** [comment]
Пока уточняю по поводу необходимости перевода лиц. соглашения на английский.

**Comment by fey** [comment]
давайте лиц. соглашения не переводить, только на русском, ссылку на него можно скрыть. по прямой ссылке пусть отображается.

**Comment by Shamatarev** [comment]
я его не приводил, а взял полностью из существующего лицензионного соглашения в корне проекта. Просто оформил через локаль.

**Comment by fey** [comment]
Ох, тогда давайте удалим и будем использовать только ру версию. Перевод лиц соглашения пока точно не нужен.

**Comment by Shamatarev** [comment]
ну вот :( а я столько времени потратил на эту локализацию :(

**Comment by fey** [comment]
ну ничо, бывает) Можете переделать код, на скрытие сссылочек

**Comment by fey** [comment]
комментировать не нужно. Давайте новым коммитом удалим. Если что - восстановим из истории гита.
Если будет комментарий, то это будет захламнять код.

**Comment by Shamatarev** [comment]
Хорошо, переделаю сегодня.

**Comment by Shamatarev** [comment]
переделал, изменения запушил.
