### ISSUE TITLE
Нет предупреждающего сообщения в тултипе ввода имени сниппета

### ISSUE THREAD

**Issue by glazovanastasia** [hexlet-rus/runit#378]
### Summary

При некорректном вводе нет предупреждающего уведомления о доступных к использованию языка и символов, используемых в имени сниппета

### Reproduction steps

```bash
1. Создать новый сниппет
2. Отредактировать автоматически сгенерированное имя
3. В поле ввода написать "Без имени"
```

### Expected result

Отображается предупреждение "Допустимы буквы латинского алфавита, цифры и символы "- _"

### Actual result

Нет предупреждающего уведомления о доступных символах ввода
![image](https://github.com/hexlet-rus/runit/assets/127899807/ab14f33e-4424-4f65-a9be-c5a19fca6d24)

### Browsers

Chrome

### OS

Windows

**Comment by Scampik** [comment]
у меня вроде получилось решить эту проблему, поэтому забираю ее

**Comment by fey** [comment]
![image](https://github.com/hexlet-rus/runit/assets/697178/687e55e7-ace1-4200-ba5a-6654148325c2)

Актуально.

**Comment by fey** [comment]
@lena05k Привет. Возьмете задачку в работу?

**Comment by Scampik** [comment]
в деплое версия до моего пра, в актуальной все ок должно быть

**Comment by fey** [comment]
@HelenOne задеплоишь?

**Comment by Lena05k** [comment]
Задачка еще актуальна? Могу брать?

**Comment by HelenOne** [comment]
Да, действительно просто не задеплоили
Теперь в проде всё ок, задачка не актуальна больше
@Lena05k

**Comment by fey** [comment]
@Lena05k Предлагаю пофиксить вот эту штуку :)
![image](https://github.com/hexlet-rus/runit/assets/697178/523f200e-1495-4c09-8fcf-80ceb0d1bc63)

**Comment by Lena05k** [comment]
Ок. Возьму.

**Comment by Lena05k** [comment]
Вы задеплоили? У меня не показывает предупреждение.
![image](https://github.com/hexlet-rus/runit/assets/68637917/a6251a8e-43ca-4e0a-ace0-d41a3604e4dd)

И также могу без формата указать имя файла
![image](https://github.com/hexlet-rus/runit/assets/68637917/1aff750b-0f1a-4ad9-87c4-87ace12f8d6f)

**Comment by fey** [comment]
назвать без формата - это норм. мы же сниппет именуем, не файл. 
Вот свежий скрин, проверил на проде.
![image](https://github.com/hexlet-rus/runit/assets/697178/de784d84-cbd0-4a9d-9ef4-2f0435f415c4)
