### ISSUE TITLE
Нельзя сохранить имя сниппета с пробелом

### ISSUE THREAD

**Issue by glazovanastasia** [hexlet-rus/runit#379]
### Summary

Ошибка при вводе пробела в имени сниппета

### Reproduction steps

```bash
1. Создать новый сниппет
2. Отредактировать автоматически сгенерированное имя
3. В поле ввода написать "No name"
```

### Expected result

Имя сниппета сохранено

### Actual result

Имя не сохраняется, появляется предупреждающее уведомление

### Browsers

Chrome

### OS

Windows

**Comment by faciledictu** [comment]
Пробел сейчас не входит в число разрешенных знаков. В текущей реализации это a-z A-Z 0-9 . _ -
Есть предложение по увеличению их числа?

**Comment by fey** [comment]
Да, давайте добавим, сейчас мы имя сниппета не используем в путях, чисто для отображения юзеру.

**Comment by elenashcherbinina** [comment]
Решили добавить пробел для имени сниппета? Могу взять в работу.

**Comment by faciledictu** [comment]
Да, сделайте, пожалуйста. Это должно быть несложно.

**Comment by elenashcherbinina** [comment]
Беру в работу тогда

**Comment by fey** [comment]
@glazovanastasia можете проверить, пофиксили ли?

**Comment by glazovanastasia** [comment]
Проблема не устранена

**Comment by elenashcherbinina** [comment]
А что именно не работает? Пробел я добавила. Пулреквест сделала, не уверена, что ушло в прод. Но у меня локально можно добавлять имя сниппета с пробелом.

**Comment by glazovanastasia** [comment]
@elenashcherbinina неа, по-прежнему ругается
![image](https://github.com/hexlet-rus/runit/assets/127899807/d3b1e246-b99f-491d-9751-fdeffaa79b1e)

**Comment by fey** [comment]
@glazovanastasia можете чекнуть, пофикшено ли?

**Comment by glazovanastasia** [comment]
@fey да, ура!
