### ISSUE TITLE
Cсылка на восстановление пароля

### ISSUE THREAD

**Issue by elenashcherbinina** [hexlet-rus/runit#381]
### Problem description

Cейчас ссылка на восстановление пароля на форме входа отображается только, если ввели неверно пароль. 

### Proposed solution

Отобразить ее сразу, чтобы без ввода неверного пароля можно было восстановить себе доступ.

**Comment by elenashcherbinina** [comment]
беру в работу

**Comment by faciledictu** [comment]
Раньше было красиво: две кнопки входа одна под другой. А теперь кнопка логина справа. Может, сделать кнопку на всю ширину, а ссылку ниже (туда, где сейчас предложение зарегистрировать новый аккаунт)? Кажется, что некрасиво, что кнопки разные. Или норм?

**Comment by elenashcherbinina** [comment]
Дима привет! Да я думала об этом, когда добавляла ссылку. Но, если сделать кнопку во весь контейнер, а ссылку ниже, то например, когда я ввожу неправильный пароль, то меня переправляет на "не помню пароль" и он выглядит именно так, как выглядит сейчас. Мне показалось некрасиво, когда сначала ссылка в одном месте, а потом она перемещается в другое. 

Но ты прав, когда одна длинная кнопка более эстетично смотрится. Можно тогда переделать обе страницы, чтобы была одна большая кнопка, а сверху справа "не помню пароль", но чтобы на обеих страницах было одинаково.
