### ISSUE TITLE
Bug:  Создание одним авторизованным пользователем несколько сниппетов с пустым именем в одном языке программирования

### ISSUE THREAD

**Issue by kairina2020** [hexlet-rus/runit#391]
### Summary

Авторизованный пользователь создавая новый сниппет на JS может сохранить его под пустым именем. Таким образом можно создать несколько сниппетов без "возражения" сервиса.

В Allure OPEN Defect #397 Есть возможность создать сниппет с пустым именем.

Bag#212  с такой же ошибкой был закрыт для прошлой версии. В этой повторился. 

### Reproduction steps

```bash
Test-case #2377 Создания сниппета с пустым именем
Precondition
Пользователь авторизован и открыто окно со сниппетами

Scenario
1 На кнопке "Новый сниппет" нажать на иконку языка программирования
2 В открывшемся окне сниппета в поле имени нажать на иконку "карандаш"
3 Удалить все символы имени
4 Enter
5 Кликнуть по "Мои сниппеты " в верхнем меню
```

### Expected result

Невозможно создать сниппет с пустым именем

### Actual result

Сниппеты с пустым именем можно создать. Даже несколько.
![image](https://github.com/hexlet-rus/runit/assets/110185387/eb7eb0df-4cb1-4a48-82f5-98db12511bbe)
![image](https://github.com/hexlet-rus/runit/assets/110185387/a82628cf-daf6-4ef3-8eed-b83f0a78ce96)
![image](https://github.com/hexlet-rus/runit/assets/110185387/90e26ebd-885a-4a46-a3b6-424a39879654)

### Browsers

Chrome

### OS

Windows

**Comment by kairina2020** [comment]
@fey , Николай, в том проекте закрыла баг, в этом открыла .
Мне для себя можете сказать, это является багом? или это предусмотренная возможность по документации)

**Comment by kairina2020** [comment]
Ну если несколько сниппетов на одном языке написаны, то как минимум неудобно и непонятно))).

**Comment by nick-shaydayuk** [comment]
Привет! Мне кажется, что всё-таки стоит добавить валидацию на пустоту. Могу взять в работу :)

**Comment by fey** [comment]
Давайте поизучаем, как это выглядит на других сервисах, например на код пене. 
`.js`- это часть имени сниппета. Т.е. имя сниппета уже не пустое. А вот прям пустое-пустое имя вроде нельзя создать.

**Comment by nick-shaydayuk** [comment]
На кодпене реализовано так: 
 Создать без названия можно, но в списке работ будет отображаться, как "pen by NickName", принцип работает для любого количества сниппетов
 С реплитом проще, он не даёт в принципе создать сниппет без названия

**Comment by fey** [comment]
Сейчас сниппеты создаются без разширения, а без имени создать/редактировать нельзя
