### ISSUE TITLE
Нет автообновления скролла

### ISSUE THREAD

**Issue by geophyzik** [hexlet-rus/runit#392]
## Summary

При переходе на другую страницу, React не изменяет положение скролла по умолчанию.

## Reproduction steps

> 1. Нажать на  мои сниппеты
> 2. Прокрутить вниз
> 3. Открыть любой сниппет

## Expected result
При переходе на другую страницу положение скролла стоит в начале 

## Actual result
При переходе на другую страницу приходится докручивать скролл 🙃

**Comment by SamIvan-ark** [comment]
Я попробую взять, если никто не против

**Comment by dzencot** [comment]
А можете плз подробней про баг рассказать? Просто я проверяю и такого не происходит, скролится при переходе. Может что-то не так делаю

**Comment by SamIvan-ark** [comment]
Иван, привет!
Чтобы словить баг, нужно сначала сделать так, чтобы появился скролл на странице (например, создать много сниппетов, чтобы они расположились в два ряда), потом покрутить ее немного вниз и переместиться на другую страницу, например, в сниппет.
В после перехода на страницу со сниппетом, скролл должен восстановиться до координаты (0, 0), но он остается на том же месте, где был.
Это не совсем баг, а скорее особенность реакт-роутера, исправляется компонентом-костылем из [документации](https://v5.reactrouter.com/web/guides/scroll-restoration))

**Comment by dzencot** [comment]
![example-2023-10-24_22 06 35](https://github.com/hexlet-rus/runit/assets/3888419/8119f39e-c991-45b8-8dcb-860944e1f89a)
Так и проверяю

**Comment by dzencot** [comment]
Может от браузера зависит? Пр принял
