### ISSUE TITLE
Bug: всплывашка редактора в на сайте перекрывается верхней панелью

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#399]
### Summary

![image](https://github.com/hexlet-rus/runit/assets/697178/047ef192-5fc6-4905-9c2e-95987c00d95d)

### Reproduction steps

```bash
1. создаем сниппет с кодом
2. наводим курсор на какой-нибудь элемент
```

### Expected result

Попап отображается корректно

### Actual result

Попап перекрывается верхней панелью

### Browsers

Chrome

### OS

Linux

**Comment by niramov** [comment]
Беру в работу

**Comment by fey** [comment]
да, пап должен оторажаться целиком. Думаю это можно сделать разными способами - выводить всегда на самый верхний слой, либо увеличить отступ между верхней панелью и редатором

**Comment by fey** [comment]
![image](https://github.com/hexlet-rus/runit/assets/697178/9cb50246-bb82-4073-93c8-98555f66e36b)

cool!
