### ISSUE TITLE
Bug: Supported language

### ISSUE THREAD

**Issue by geophyzik** [hexlet-rus/runit#401]
### Summary

С ласт пра сняли заглушку на пхп и питон

### Reproduction steps

```bash
1. Мои сниппеты
2. Создаем сниппет пхп или питон, открывается терминал js
```

### Expected result

Надо поставить заглушки или убрать не поддерживаемые языки

### Actual result

Создаются сниппеты с не поддерживаемыми языками

### Browsers

Chrome

### OS

Mac

**Comment by elenashcherbinina** [comment]
возьму в работу. Что значит поставить заглушку? Просто сделать, чтобы язык был виден, но его нельзя была выбрать? Или полностью скрыть php и python?

**Comment by Scampik** [comment]
заглушка
![image](https://github.com/hexlet-rus/runit/assets/115660566/cd28753b-c61d-4d17-80ea-753e8b2f23dc)
