### ISSUE TITLE
bug: некорректная ширина предупреждающего тултипа при смене имени сниппета

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#403]
![image](https://github.com/hexlet-rus/runit/assets/697178/20af2a19-4142-433e-a9c6-a0f4d735fd06)

@Lena05k завел в отдельный ищщус, чтобы не потерялсь.

**Comment by fey** [comment]
![image](https://github.com/hexlet-rus/runit/assets/697178/432a3c99-0d2b-4fe4-878e-083b4ddc276a)

**Comment by Lena05k** [comment]
Подойдет?
![изображение](https://github.com/hexlet-rus/runit/assets/68637917/7133c5c2-5172-4303-852b-855975fb35bb)
![изображение](https://github.com/hexlet-rus/runit/assets/68637917/348e7c77-75ba-4cbc-819c-6b19dfeb72d5)
![изображение](https://github.com/hexlet-rus/runit/assets/68637917/ade50f48-6491-4973-868a-b19ec6bf6620)

**Comment by fey** [comment]
Думаю да. присылайте ПР =)

**Comment by fey** [comment]
https://github.com/hexlet-rus/runit/pull/404
