### ISSUE TITLE
Вид сниппет тулбара 

### ISSUE THREAD

**Issue by geophyzik** [hexlet-rus/runit#407]
### Problem description

В тулбаре съехал карандаш, т.к. под название сниппета сейчас стоит фиксированная ширина

<img width="400" alt="Снимок экрана 2023-10-25 в 09 56 18" src="https://github.com/hexlet-rus/runit/assets/115660566/b5f7b6f3-fc08-4050-876a-594d44eabd06">

### Proposed solution

попробовал исправить
думаю так будет симпатичнее  смотреться 

<img width="400" alt="Снимок экрана 2023-10-25 в 09 56 18" src="https://github.com/hexlet-rus/runit/assets/115660566/16badb1c-10d3-4c33-a615-6b00d1ff924d">

тултип фидбека не пострадал

<img width="200" alt="Снимок экрана 2023-10-25 в 09 56 18" src="https://github.com/hexlet-rus/runit/assets/115660566/746fdfee-5292-42e2-846d-a7bba0883362">

<img width="260" alt="Снимок экрана 2023-10-25 в 09 56 18" src="https://github.com/hexlet-rus/runit/assets/115660566/9f7fbbb9-120f-46c1-9a80-7e50d535b56b">

**Comment by geophyzik** [comment]
забрал

**Comment by vyacheslav-pv** [comment]
Актуально? беру
