### ISSUE TITLE
Bug: Исправить цвет текста при активной вкладке

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#410]
### Summary

Сейчас текст сливается с фоном
<img width="483" alt="image" src="https://github.com/hexlet-rus/runit/assets/77053797/851f0943-0019-4ad6-aab9-cfa0fe90b787">

### Reproduction steps

```bash
На главной странице https://runit.hexlet.ru/ в блоке FAQ, при нажатии на вкладку в аккордеоне, текст становится синего цвета и сливается с фоном
```

### Expected result

Текст должен быть читабельным

### Actual result

.

### Browsers

Chrome

**Comment by RossJeanCarter** [comment]
взял в работу

**Comment by RossJeanCarter** [comment]
Я так понимаю проблему исправили? Я вроде, написал, взял в работу, а в итоге, кто-то issue взял.

**Comment by elenashcherbinina** [comment]
возьму в работу
