### ISSUE TITLE
Не реализована функция удаления учетной записи пользователя

### ISSUE THREAD

**Issue by ElenaSimanina** [hexlet-rus/runit#419]
### **_Не реализована функция удаления учетной записи пользователя_**
1. Авторизоваться
2. Открыть настройки учетной записи пользователя [https://runit.hexlet.ru/settings](https://runit.hexlet.ru/settings)
3. Кликнуть на кнопку "Удалить учетную запись" внизу формы настройки учетной записи
4. Появляется сообщение "Эта функция пока недоступна"

![Screen_2](https://github.com/hexlet-rus/runit/assets/135851722/d0911bf8-e54a-46a0-8a4c-370c39c359b6)

### Proposed solution

Реализовать функцию удаления учетной записи пользователя

**Comment by bobronaud** [comment]
Работаю над задачей
