### ISSUE TITLE
Не реализован сервис восстановления пароля

### ISSUE THREAD

**Issue by ElenaSimanina** [hexlet-rus/runit#420]
### ****На** электронную почту пользователя не приходит сообщение с инструкцией по восстановлению пароля. Пользователь не может восстановить пароль.**
**Предусловия:**
- пользователь авторизован
- отрыта страница [https://runit.hexlet.ru/signin](https://runit.hexlet.ru/signin)

 **Шаги:**
1. Кликнуть на кнопку "Не помню пароль"
2. Ввести адрес электронной почты в форму восстановления пароля
3. Кликнуть на кнопку "Сбросить пароль"
4. Проверить появление сообщения об отправлении инструкции по восстановлению пароля на электронную почту пользователя
5. Открыть  электронную почту
6. Проверить получение инструкции по восстановлению пароля

  **_Фактический результат: **_На электронную почту пользователя не приходит письмо с инструкцией по восстановлению пароля_**_**

### Proposed solution

Реализовать сервис по восстановлению пароля пользователя

**Comment by bobronaud** [comment]
[Снимаюсь с задачи.](https://github.com/hexlet-rus/runit/issues/416#issuecomment-1938853656)

Задачка СВОБОДНА, можно брать.

**Comment by Loresina** [comment]
Я привильно понимаю. что эту задачу можно (или нужно)  сделать через unisender api ?
Судя по тому, что обсуждали здесь [issues 416](https://github.com/hexlet-rus/runit/issues/416)

**Comment by fey** [comment]
@Loresina вообще, через любой smtp сервис, но да, через юнисендер мы хотим отправлять письма. Креды есть, но что-то не доделали :thinking:

**Comment by Loresina** [comment]
ок. пробую разобраться. Беру эту  задачу.

**Comment by fey** [comment]
На всякий случай напомню, что здесь потребуется поковырять бекенд

**Comment by fey** [comment]
fixed https://github.com/hexlet-rus/runit/commit/4298eb4bae598b5c8ec5a280bd5c688821e4b3e2
