### ISSUE TITLE
Не реализована функция "Поделиться профилем"

### ISSUE THREAD

**Issue by ElenaSimanina** [hexlet-rus/runit#423]
### **Пользователь не может поделиться своим профилем. Появляется сообщение "Эта функция пока недоступна"**

1. Кликнуть на изображение профиля в верхнем правом углу сайта
2. Кликнуть на кнопку "Поделиться профилем"
3. Проверить наличие возможности поделиться профилем

![chrome_bst8tPs3zy](https://github.com/hexlet-rus/runit/assets/135851722/1bf25337-e68a-4af5-8c51-6984ac5150ab)

### Proposed solution

Реализовать функцию "Поделиться профилем"

**Comment by bobronaud** [comment]
@fey @dzencot 
Объясните, пожалуйста, что под собой подразумевает "поделиться профилем"? Не могу сообразить. Я понимаю, как можно поделиться сниппетом, но не понимаю, как можно поделиться профилем и как это должно быть реализовано.

**Comment by fey** [comment]
По идее поделиться профилем - скинуть ссылку на свой профиль.
Я бы предложил пока этот пункт из меню убрать. 

Пока что у нас нет публичных профилей, т.е. ссылка на мой профиль будет 404 отдавать https://runit.hexlet.ru/u/fey
