### ISSUE TITLE
Bug: Ошибка копирования сниппета

### ISSUE THREAD

**Issue by ElenaSimanina** [hexlet-rus/runit#428]
### Summary
Пользователь не может скопировать сниппет

### Reproduction steps

```bash
1. Открыть страницу https://runit.hexlet.ru/
2. Авторизоваться
3. Выбрать сниппет 
4. Нажать на кнопку выбора меню (три вертикальных точки) на сниппете
5. Нажать на кнопку копирования из открывшегося меню 
6. Нажать на кнопку "Подтвердить"  в открывшемся сообщении
7. Проверить , что сниппет  успешно скопирован)





```
### Expected result

Сниппет успешно скопирован

### Actual result

появляется сообщение "Ошибка сети", сниппет не скопирован

![Screen_4](https://github.com/hexlet-rus/runit/assets/135851722/ffce8eb5-347c-410f-a9b8-061379f7e99e)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
подтверждаю, баг воспроизводится.

**Comment by bobronaud** [comment]
нашёл в чем ошибка, сейчас все сделаю

но заранее хочу сказать, что [доку апи](https://runit.hexlet.ru/api#/) нужно обновить.

в проекте метод POST api/snippets ожидает три аргумента {code, name, language}

а в доке ожидает только два аргумента {code, name}

поэтому ошибка сети (400) приходит, т.к. вместо ожидаемых трёх аргументов, приходит два.

**Comment by bobronaud** [comment]
@fey еще уточнить хочу.
Сейчас при копировании сниппета, он создается в профиле и происходит редирект на новый спиппет-копию.
Как-то не очевидно, что при нажатии кнопки "копировать" произойдет редирект на копию.

**Comment by fey** [comment]
почему? Можем назвать по другому кнопку, например "Fork". В гитхабе такая же логика - вы форкаете репоиторий и открывается страница с редактированием.

Еще проверьте, выводится ли модалка, когда открывается редактор с копией сниппета. Хорошо бы пользователю писать, что произошло, типа "сниппет успешно скопирован"

**Comment by fey** [comment]
по идее надо на бекенде поправить, чтобы он три параметра принимал. @dzencot поможешь с доработкой бекенда?
