### ISSUE TITLE
Не реализована функция по созданию нового сниппета по шаблону HTML

### ISSUE THREAD

**Issue by ElenaSimanina** [hexlet-rus/runit#432]
### Problem description

1. Открыть страницу https://runit.hexlet.ru/
2. Авторизоваться
3. Кликнуть на  изображение профиля пользователя
4. Нажать "Новый сниппет"
5. Выбрать шаблон HTML
4. Заполнить поле "Название"
5. Нажать кнопку "Создать"

_ОР: новый сниппет успешно создан и отображается на странице сниппетов
ФР: отсутствует шаблон HTML, функция не реализована_

![Screen_5](https://github.com/hexlet-rus/runit/assets/135851722/31731324-f227-4f58-b60b-34ee9ce757f1)
![Screen_6](https://github.com/hexlet-rus/runit/assets/135851722/ec2cb1c2-d63d-49cb-a06b-331e21aefd32)
![Screen_7](https://github.com/hexlet-rus/runit/assets/135851722/876af825-ec72-4dbe-b86e-9dccccc172f8)

### Proposed solution

Реализовать функцию по созданию нового сниппета по шаблону HTML

**Comment by bobronaud** [comment]
взял в работу

**Comment by fey** [comment]
@ElenaSimanina Можете проверить результат?

**Comment by fey** [comment]
@ElenaSimanina https://github.com/hexlet-rus/runit/pull/433 в ПРе есть ссылка на демо.

**Comment by ElenaSimanina** [comment]
Проверила)
Баг исправлен, пользователь может выбрать шаблон HTML, новый сниппет создан и отображается на странице сниппетов. 

![Screen_8](https://github.com/hexlet-rus/runit/assets/135851722/fb9677cd-0277-4085-9f77-af1e74ab90bc)
![Screen_9](https://github.com/hexlet-rus/runit/assets/135851722/251bda15-af03-4729-b6d8-24d1beba4577)
