### ISSUE TITLE
переключить лендинг и добавить ссылку на кодинг бе регистрации

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#434]
### Problem description

Пора переключаться на лендос https://runit.hexlet.ru/landing

### Proposed solution

Выносим его на главную, добавляем со старого лендоса ссылку для кодинга без регистрации
![image](https://github.com/hexlet-rus/runit/assets/697178/e7b00f53-ff62-40cf-bda2-4a0f754a46b0)

**Comment by fey** [comment]
@bobronaud как успехи?

**Comment by bobronaud** [comment]
@fey в процессе, делаю)

**Comment by bobronaud** [comment]
@fey , так норм или полоски перекрывают?

<img width="886" alt="image" src="https://github.com/hexlet-rus/runit/assets/89943183/ad12f1b4-6a44-405d-9d09-acc05a6ed0a7">

**Comment by fey** [comment]
а если добавить фон на кнопку?

**Comment by bobronaud** [comment]
@fey синий или черный
<img width="890" alt="image" src="https://github.com/hexlet-rus/runit/assets/89943183/420b3ddd-eb67-403c-8cb1-5725ef874ff8">
<img width="932" alt="image" src="https://github.com/hexlet-rus/runit/assets/89943183/fb310bd1-bdfe-4e90-a885-8d0b16efbcd9">

**Comment by fey** [comment]
кнопку лучше сделать контрастной. Т.е. если белый фон - то белую кнопку, если темный - то черный. Т.е. можно взять цвет с подложки.

**Comment by fey** [comment]
нет, если фон белый, то кнопку белой, тогда кнопка будет сливаться с фоном, но под кнопкой не будет полосок - она не будет прозрачной
