### ISSUE TITLE
bug: при создания html гостем в имени сниппета появляется undefined

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#439]
### Summary

![image](https://github.com/hexlet-rus/runit/assets/697178/e52d38f9-2f11-41a7-9d89-74f356548e31)

### Reproduction steps

```bash
1. Начать Try without registration
2. Выбрать язык html
3. ждем загрузки и смотрим на название сниппета
```

### Expected result

Сниппет не содержит undefined, либо содержит html

### Actual result

На скриншоте.

### Browsers

Chrome

### OS

Linux

**Comment by fey** [comment]
@igshipilov тут не подскажу. Давайте попросим помощи у @HelenOne 
Вообще можете попробвоать аишку глянуть, может там внутри найдете что-то про генерацию имени =)

ВОообще кажется что нам расширение не нужно особо.

**Comment by igshipilov** [comment]
@fey 

А как могу посмотреть результаты внесённых изменений? Что бы я ни делал в коде, после команды `make start` всё работает без изменений, даже если удалил целый блок кода из `render()` в модуле.

Ещё пробовал сначала `make build` потом `make start`, но тоже не вижу влияние изменений в коде.

**Comment by bobronaud** [comment]
@igshipilov у меня тож такое было, когда я впервые развернул проект.
не помню как я это исправил, но проблема в том, что ты запускаешь продакшн проекта, поэтому изменения кода не обровляют твою страницу

**Comment by bobronaud** [comment]
make build тебе тут не нужен, что начать разрабатывать

**Comment by igshipilov** [comment]
@bobronaud Принял, `make build` не нужен

**Comment by igshipilov** [comment]
@bobronaud Да, идею уловил, спасибо!

Опишу свои действия:

1. Зашёл по пути: `frontend/src/pages/snippet`
2. Нахожу соответствующий текущей задаче модуль, в данном случае мне кажется что это `FileToolbar.jsx`
3. Меняю блок кода, который понимаю. Например, просто чтобы увидеть изменения, попытался удалить [строчку 36](https://vscode.dev/github/hexlet-rus/runit/blob/main/frontend/src/pages/snippet/FileToolbar.jsx#L35), `filenameInput.setSelectionRange(0, filenameInput.value.lastIndexOf('.'));`
4. `Ctrl + C`, затем `make start`
5. Клик по аватарке → Новый сниппет → html → "Создать"
6. Кликаю по иконке карандаша (переименовать)
Ожидаю, что выделится весь текст.
По факту выделяется текст до точки – то есть как будто я не удалял ту строчку.

Ещё я подумал, что вдруг неправильно понял работу этой строчки. Поэтому для верности снёс всё из `render()`, то есть начиная с [78 строчки](https://vscode.dev/github/hexlet-rus/runit/blob/main/frontend/src/pages/snippet/FileToolbar.jsx#L78) – опять же, чтобы проверить, влияют ли мои изменения на результат. Но нет, всё рендерится нормально, никаких ошибок не возникает – будто бы код сохранён в каком-то буфере, не знаю.

**Comment by bobronaud** [comment]
то что ты удаляешь все из рэндера с 78 строчки, это ты удаляешь рендер из функции SnippetName(), которая начинается с 20 строки. То есть это не компонент тулбара, который рендерит иконку, название, карпандаш, облачко.
ты попробуй в этом же файле удалить 160-165 строчки удалить и заменить на `return <p>lol</p>`

**Comment by igshipilov** [comment]
Хотя вряд ли браузер – зашёл через другой, тоже нет результата

**Comment by bobronaud** [comment]
кинь скрин терминала на весь экран

**Comment by igshipilov** [comment]
Выглядит целым, вроде: ![2024-03-20_22-02-24](https://github.com/hexlet-rus/runit/assets/57264879/f9b0db35-5a0b-43f5-a9d5-cca4ab966c67)

**Comment by igshipilov** [comment]
Я на сегодня уже отключаюсь

**Comment by fey** [comment]
Ребят, если что можете например в телеге, в канале "Волонтеры" продолжить https://t.me/hexletcommunity/12
Там могут подключиться и другие ребята.

**Comment by bobrov-site** [comment]
@fey проблема является еще актуальной?

**Comment by fey** [comment]
Связанного пулл реквеста не помню. @Yawerica можете, пожалуйста, проверить?

**Comment by bobrov-site** [comment]
#469 я помню, что здесь решалась проблема. по-моему, я ее и решил. #470 решал тут
