### ISSUE TITLE
Нет пробела после ключевых слов

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#440]
### Summary

В разделах: 

1. Какие инструменты IDE помогают разработчикам? 
2. Какие бывают IDE?

"Жирные" слова не отделены пробелами со следующим словом.
В английской раскладке после "Жирных" слов стоит bullet point.

### Reproduction steps

```bash
1. Перейти на страницу https://runit.hexlet.ru/about
2. Открыть раздел Какие инструменты IDE помогают разработчикам? 
3. Открыть раздел Какие бывают IDE?
4. Открыть те же разделы на английской раскладке
```

### Expected result

После "жирных" слов идут пробелы

### Actual result

![нет пробела англ](https://github.com/hexlet-rus/runit/assets/148934630/a3d2029b-7b18-48d4-91e3-a7c21590a049)
![нет пробела1](https://github.com/hexlet-rus/runit/assets/148934630/5e97b472-6a49-4f67-a86b-9bc7e375133d)
![нет пробела2](https://github.com/hexlet-rus/runit/assets/148934630/71f8f4b8-ace4-4636-8933-403e81a641a5)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
По идее тут стоит переверстать тексты с переводами и закинуть в файл переводов html с нужной версткой и рендерить как html. Тогда в файлах переводов можно будет бахнуть пробельчик и не мучаться с ним в компоненте

**Comment by fey** [comment]
да, берите :+1:

**Comment by IVANn84** [comment]
Можно перевести в закрытые . проблема давно решена (просто для порядка))
