### ISSUE TITLE
Создать кнопку Сохранить на страницу сниппета

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#441]
### Problem description

Отсутствует кнопка Закрыть в открытом сниппете

### Proposed solution

Создать кнопку Закрыть. Кнопка несет чисто психологический характер)
 возможно лучше не просто Закрыть, а **Сохранить и Закрыть**

### Solution

Добавляем кнопку "Сохранить" для сохранения сниппета вручную.

![добавить кнопку закрыть](https://github.com/hexlet-rus/runit/assets/148934630/a1d729b0-345f-4216-835e-0266e32eb0f5)

**Comment by bobrov-site** [comment]
Я могу попробовать взять в работу, если ишью актуальное

**Comment by bobrov-site** [comment]
У меня возник по работе кнопки. Как ее нужно сделать в конечном счете? Я изначально подумал, что если нажать на кнопку сохранить, то сохраняется код (просто вызываем принудительное сохранение) и нас перебрасывает в мои снипеты. 

Просто если кнопка будет работать, как просто сохранение - то смысла в ней нет, так как код итак сохраняется, когда мы создаем файл или же просто что-то написали

**Comment by bobrov-site** [comment]
Добавил пулреквест, дайте пожалуйста уточнение по работе кнопки. Если что подправлю

**Comment by Yawerica** [comment]
Считаю, что для пользователя неочевидно, что код сохраняется автоматически. 
Облачко со словом Сохранено не достаточно убедительно. Может его как то выделить? или я не права?)

**Comment by fey** [comment]
@Yawerica если выделение, то она то может может появиться визуальный шум, от которого придется избавиться. 
Пока попробуем с кнопкой сохранения, ну и дальше будем улучшать интерфейсы.

**Comment by fey** [comment]
> Просто если кнопка будет работать, как просто сохранение - то смысла в ней нет, так как код итак сохраняется, когда мы создаем файл или же просто что-то написали

кнопка должна сохранять сниппет. Вполне может быть такое. что автосохранение не сработает. Если вам нужно будет сохранить сниппет, то придется его изменять, внося ненужные изменения. А по кнопке вы можете сохранить его, не меняя.

**Comment by faciledictu** [comment]
Совершенно не согласен с тем, что нужна кнопка "сохранить". Она только путает пользователя и замусоливает интерфейс. Сохранение происходит автоматически. Надпись о том, что код сохранен – куда же убедительнее? :) Это фактический стандарт работы с облачными редакторами. 
Давайте посмотрим, как реализовано сохранение в облачных сервисах
<img width="1392" alt="Google Drive Undsaved" src="https://github.com/hexlet-rus/runit/assets/104712148/179d4d02-0f83-45f8-9a9f-ebc8db085e66">
<img width="1392" alt="Google Drive Saved" src="https://github.com/hexlet-rus/runit/assets/104712148/fcbd704b-d097-453a-9bf6-81bc8c8a369c">
<img width="1276" alt="Screenshot 2024-04-26 at 14 13 25" src="https://github.com/hexlet-rus/runit/assets/104712148/0434220f-54cf-4d6d-afa9-add073cecd84">

**Comment by fey** [comment]
Обкашляем с Кириллом

**Comment by faciledictu** [comment]
А вот нашел пример очень путающего паттерна. Смотри, я добавил в открытый строку с H2 прямо сейчас. И на вкладке с открытым файлом вместо крестика появилась жирная белая точка (типа файл не сохранен). Но он по факту сохранен. Я уже сейчас вижу изменение верстки в панели справа. Плюс я тупо закрыл браузер, открыл его, и в файле все изменения отображаются. Все равно он его сохранял (несмотря на точку). Его невозможно закрыть, не сохраняя изменения.
<img width="1489" alt="Screenshot 2024-04-26 at 14 30 25" src="https://github.com/hexlet-rus/runit/assets/104712148/98775e26-6376-46a1-8ac9-40243b60dd25">

**Comment by fey** [comment]
еще не созванивался. Пока кнопку оставляем, убрать всегда можем.

**Comment by Yawerica** [comment]
@fey возможно мы правда погорячились с кнопкой Сохранить.
потому что ЦА RUN IT это программисты и скорее всего такие люди знакомы с Интерфейсом облачных сервисов как говорит @faciledictu. и в курсе что Облачко в центре означает что код Сохранен. 
НО предлагаю кнопку ОЧИСТИТЬ или Иконку корзины вместо созданной кнопки Сохранить.
чтобы очистить консоль. Как в Replit например)
![кнока очистить](https://github.com/hexlet-rus/runit/assets/148934630/f26ece4c-6578-4ed3-86ee-a514767f1fa7)
извините за созданную смуту с кнопкой.

**Comment by fey** [comment]
С кнопкой пока не переживайте. Пусть будет. А насчет очистить вывод - можно добавить, да. Создайте ищщус.
