### ISSUE TITLE
Поле регистрации допускает наличие пробелов 

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#443]
### Summary

Поле  Username при регистрации допускает наличие пробелов до и после основных символов

### Reproduction steps

```bash
1. Открыть https://runit.hexlet.ru/signup
2. Ввести имя пользователя “  23456789abcdefj.”    “23456789abcdefj   ”
3. Ввести валидный email
4. Ввести корректный пароль
5. Нажать кнопку "Зарегистрироваться"
```

### Expected result

Регистрации не произойдет

### Actual result

Регистрация прошла успешно

### Browsers

Chrome

### OS

Linux

**Comment by fey** [comment]
Запретить пробельные символы :shrug: 
Необходимо усилить валидацию на бекенде и фронтенде. (как бы 2 задачи получаются)

**Comment by Heaven-Tonight** [comment]
Всем привет, возьму в работу.

**Comment by Heaven-Tonight** [comment]
В общем-то проверка на пробелы "до" / "после" и "внутри" username уже реализована и на фронте и на бэке. 
Я подправила код совсем немного, что бы эта проверка срабатывала.

В поле e-mail то же самое - можно ввести сколь угодно пробельных символов до и после, и регистрация пройдет успешно, т.к. валидация сама автоматически обрезает пробельные символы в начале и конце.

Может быть добавить для этих полей слушатель, который сам по себе не даст ввести пробельный символ?

**Comment by fey** [comment]
Да, давайте.

**Comment by faciledictu** [comment]
А почему в #451 решили ограничивать имя пользователя только латинскими буквами? Не вижу проблемы в смайлика или кириллице. Имя не используется для логина, оно используется в адресной строке, но там никаких проблем с юникодом тоже нет

**Comment by Yawerica** [comment]
the bug has been fixed. Thanks for the work
