### ISSUE TITLE
Некорректно отображается Уведомление на мобильном устройстве

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#444]
### Summary

Уведомление **Сохранено** выходит за границы поля сайта

precondition: 
Авторизоваться на сайте

### Reproduction steps

```bash
1. Открыть сайт https://runit.hexlet.ru/
2. С помощью окна new snippet создать новый сниппет
3. Обратить внимание на уведомление Сохранено справа вверху


environment: Эмулятор devtools / iphone5/SE / 320x560 

Так же верстка съезжает при разрешении 360х640, 320х658
```

### Expected result

Уведомление **Сохранено** не выходит за границы экрана

### Actual result

<img width="1440" alt="Screenshot 2024-03-19 at 13 27 43" src="https://github.com/hexlet-rus/runit/assets/148934630/5e5e47e0-d8d9-43ca-b6f6-244ba6d2bf51">

### Browsers

Chrome

### OS

Linux

**Comment by Yawerica** [comment]
Этот дефект, потому что у сайта нет мобильной версии? и лучше было бы написать Feature request **Адаптировать сайт для мобильных устройств?**

**Comment by vyacheslav-pv** [comment]
Взял в работу другое ишшью, оно должно покрыть это.

**Comment by vyacheslav-pv** [comment]
взял в работу

**Comment by Yawerica** [comment]
@fey баг пофиксили. можно закрывать.)
