### ISSUE TITLE
Не работает кнопка "Войти"

### ISSUE THREAD

**Issue by dinzhev** [hexlet-rus/runit#449]
### Summary

Не работает кнопка "Войти", после возвращения на предыдущую страницу

### Reproduction steps

```bash
1. На главной странице нажать кнопку "Кодить без регистрации"
2. Выбрать любой шаблон
3. Ввести название для шаблона
4. Кликнуть кнопку создать
5. Вернуться на предыдущую страницу
6. Нажать кнопку "Войти"
```

### Expected result

Появится форма для входа

### Actual result

Перенаправление на страницу гостя, с созданным сниппетом

304 Not Modified

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
по идее, если пользователь вошел (а кодить без регистрации по сути и есть вход), то должно редиректить с главной на страницу сниппетов. 
На странице сниппетов в меню можно добавить "вход", чтобы можно было залогиниться

**Comment by Heaven-Tonight** [comment]
Всем привет, это тоже возьму.

Редирект оставляем как есть, правильно же?

**Comment by fey** [comment]
@Heaven-Tonight если пользователь - зарегистрированны пользователь или гость (т.е. нажал кодить без регистрации), то редиректим на страницу снппетов.

**Comment by fey** [comment]
https://github.com/hexlet-rus/runit/pull/467
https://github.com/hexlet-rus/runit/pull/481#issuecomment-2096501363
