### ISSUE TITLE
Кнопка "Регистрация" выходит за границы отображения сайта

### ISSUE THREAD

**Issue by dinzhev** [hexlet-rus/runit#453]
### Summary

Кнопка "Регистрация" выходит за границы отображения сайта, при разрешении экрана по ширине от 992px

![Безымянный](https://github.com/hexlet-rus/runit/assets/43177015/957507b4-380f-4fe2-987d-afd727c1e1a7)

### Reproduction steps

```bash
1. На главной странице перейти в режим разработчика
2. Кликнуть "Toggle device toolbar"
3. Из выпадающего списка выбрать "Responsive"
4. Задать ширину в 992px
```

### Expected result

Кнопка "Регистрация" не выходит за границы отображения сайта

### Actual result

Кнопка "Регистрация" выходит за границы отображения сайта

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
Если ширина экрана узкая, то меню сверху должно свернуться в аккордеон, чтобы аккуратно вывестись на экране, можно посмотреть поведение на Хекслете, код бейзиксе

**Comment by bobrov-site** [comment]
взял в работу
