### ISSUE TITLE
Feature request: Добавить кнопку change view

### ISSUE THREAD

**Issue by bobrov-site** [hexlet-rus/runit#465]
### Problem description

На сайте https://codepen.io/ есть удобная функция смена вида:

<img width="298" alt="Снимок экрана 2024-04-17 в 14 32 24" src="https://github.com/hexlet-rus/runit/assets/39225852/0a84a1d5-aeb3-485e-9acb-72839072a580">

Она позволяет менять вид редактора кода: вертикально, горизонтально.

В нашем коде, есть уже поддержка direction: horizontal и vertical. Пока, что она используется при переходе с мобильных на десктопные устройства (если быть точнее мы просто используем useMediaQuery('(min-width: 768px)'); для отображения двух состояний).

**Зачем нужна эта кнопка?**

На устройствах например макбук, удобнее работать именно в горизонтальном режиме, чтобы код как можно больше располагался вертикально и горизонтально. Иногда просто банально удобнее переключиться на такой вид.

### Proposed solution

Приблизительный результат:
<img width="1669" alt="Снимок экрана 2024-04-17 в 14 39 52" src="https://github.com/hexlet-rus/runit/assets/39225852/4729f67a-24c2-4812-b0bc-a2051cb187c3">

1. Добавить кнопку отображения вида. Пока что имеет 2 состояния: вертикальный, горизонтальный. (на скриншоте иконка вертикальлная, просто для примера, при таком виде будет другая иконка)
2. Добавить состояние в слайс редактора. В дальнейшем количество "видов" можно увеличить, опять же как на кодпене, добавить вид слева или справа. Но пока что на первом этапе добавить только вертикальный и горизонтальный.
3. Оставить данную функцию только на устройствах от 768px. На мобильных телефонах эта история будет не очень актуальная, поэтому просто оставим решение как раньше, а вот на планшетах и десктопах добавить возможность переключения, но сделать поумолчанию горизонтальный вид.

Готов допилить задачу. Уже написал немного кода

**Comment by bobrov-site** [comment]
Несколько комитов можно посмотреть тут https://github.com/bobrov-site/runit/tree/ViewButtonForEditor

**Comment by fey** [comment]
Да, давайте попробуем кнопку дообавить.

**Comment by JS-Demi** [comment]
Готов взять в работу

**Comment by bobrov-site** [comment]
@JS-Demi уже пулреквест висит https://github.com/hexlet-rus/runit/pull/466 . Но если потребуется помощь, обращусь!
