### ISSUE TITLE
Проблема с вертской в FAQ

### ISSUE THREAD

**Issue by Pauluson** [hexlet-rus/runit#468]
### Summary

Не работают теги в FAQ на главной странице

### Reproduction steps

```bash
1. Открыть главную страницу
2. Просмотреть все подпункты меню FAQ
```

### Expected result

Текст отображается корректно

### Actual result

Не работают теги html
Текст не читабилен
![Screenshot from 2024-04-23 15-19-16](https://github.com/hexlet-rus/runit/assets/36787627/36899c8e-b196-44d6-93c9-e73d2a518def)
![Screenshot from 2024-04-23 15-19-51](https://github.com/hexlet-rus/runit/assets/36787627/0049f771-ab82-4cfc-9059-a63913f89b72)

### Browsers

Chrome

### OS

Linux

**Comment by bobrov-site** [comment]
Готов взять в работу

**Comment by bobrov-site** [comment]
Могу взять в работу
