### ISSUE TITLE
Неправильное расширение в сниппет

### ISSUE THREAD

**Issue by Pauluson** [hexlet-rus/runit#469]
### Summary

При первом создании html сниппета в режиме гостя, повляется неправильное расширение 

### Reproduction steps

```bash
1. Открыть главную страницу в режиме гостя
2. Нажать на кнопку "Кодить без регистрации"
3. Выбрать шаблон html
4. Ввести название
5. Нажать на кнопку создать
```

### Expected result

Сниппет создался с привильным расширением

### Actual result

Сниппет создался с расширением `"undefined"`
![Screenshot from 2024-04-23 15-45-21](https://github.com/hexlet-rus/runit/assets/36787627/e893b970-6222-4467-a2de-5ec10f996db3)

### Browsers

Chrome

### OS

Linux

**Comment by bobrov-site** [comment]
Готов взять в работу

**Comment by bobrov-site** [comment]
@Pauluson подскажите пожалуйста, где вы вводите название сниппета? Не могу повторить сценарий провала, так как у меня корректно отображается расширение

**Comment by Pauluson** [comment]
@bobrov-site возпроизводить нужно в режиме гостя(попробуйте повторить в режиме инкогнита Crtl+Shift+N)

**Comment by bobrov-site** [comment]
Да, действительно такая ошибка, хорошо попробую исправить
