### ISSUE TITLE
Есть возможность в имени сниппета использовать пробелы

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#476]
### Summary

Могу переименовать сниппет в имя состоящее только из пробелов

### Reproduction steps

```bash
precondition: 
1. Авторизоваться на сайте
2. Создать сниппет

steps:
1. Перейти на страницу Мои сниппеты https://runit.hexlet.ru/u/QA1
2. У выбранного сниппета нажать на карандаш, для редактирования имени сниппета
3. Ввести пробелы 
4. Нажать Enter
```

### Expected result

Имя сниппета не сохранится 

### Actual result

Сниппет переименовался

![могу переименовать сниппет в пробелы](https://github.com/hexlet-rus/runit/assets/148934630/8ea021b7-4496-4ca5-89c4-7f03b30f0dab)

### Browsers

Chrome

### OS

Windows

**Comment by bobronaud** [comment]
беру в работу

**Comment by Yawerica** [comment]
приветик @bobronaud наверное я некорректно описала проблему/ имею ввиду пробелы при переименовании существующего сниппета/

https://github.com/hexlet-rus/runit/assets/148934630/84bef361-6ae1-4358-a3b9-fee3ed043213

@fey или это не баг?

у меня пока еще воспроизводится

**Comment by Yawerica** [comment]
@bobronaud при создании сниппета  через профиль название тоже из пробелов могу сделать

https://github.com/hexlet-rus/runit/assets/148934630/33a5509b-fa21-4c7f-ac61-b14904ae4b94

**Comment by fey** [comment]
еще не задеплоил

**Comment by fey** [comment]
Вроде пофикшено

**Comment by Yawerica** [comment]
проверила. все ок.
