### ISSUE TITLE
Ошибка в тексте

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#478]
### Summary

не дописан заголовок 

### Reproduction steps

```bash
precondition: 
1. Авторизоваться на сайте

steps:
1. Перейти на главную страницу https://runit.hexlet.ru/u/QA111
2. Обратить внимание на хедер сайта
```

### Expected result

ABOUT US
![about us](https://github.com/hexlet-rus/runit/assets/148934630/10980387-e6bd-4f97-98fe-36778562bbc8)

### Actual result

ABOUT

### Browsers

Chrome

### OS

Windows

**Comment by IVANn84** [comment]
Беру в работу!

**Comment by fey** [comment]
@IVANn84 тут ошибки нет. Это информация о проекте. Например на https://spatie.be/docs/laravel-html/v3/introduction страница также называется `About`
