### ISSUE TITLE
Удалить кнопку(иконку) нереализованной фичи

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#482]
Убрать кнопку(иконку) нереализованной фичи.

### Reproduction steps

```bash
precondition:
1. Быть авторизованным.

steps:
1. Зайти на главную страницу https://runit.hexlet.ru/u/zzz
2. Обратить внимание на кнопку(иконку) справа от Имени пользователя 
3. При нажатии на нее появляется окно "Эта функция пока недоступна"
```

### Expected result

эта кнопка отсутствует.

### Actual result

![не реализовано](https://github.com/hexlet-rus/runit/assets/148934630/f9b32bb7-8bc8-41a8-9bc5-1849695021eb)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
ага, это можно пока убрать

**Comment by DimRux** [comment]
Возьму в работу.

**Comment by fey** [comment]
Тут не совсем понятно, что она означает. У нас сейчас нет публичных профилей. По идее нужно делать публичную страницу профиля, выводить туда инфу, давать ссылку на профиль, например в менюшке.
Пока у нас есть другие траблы-баги, поэтому не сильно приоритетно :thinking:

**Comment by faciledictu** [comment]
@fey да, соглашусь с тобой. Сорри, мне кнопочка нравится, я ее рисовал ) Могу предложить @DimRux не удалять код, а вынести в компонент и не подключать этот компонент к странице профиля. Если, конечно, не хотите какую-то другую логику и она будет не нужна. Тогда удаляем смело. Если надо что-то нарисовать другое — обращайтесь

**Comment by faciledictu** [comment]
Вообще, сорри за занудство, но тыкать юзера, что он ввел лишние пробелы — это плохо. Типа "ну поправь пожалуйста". Ну пусть себе вводит хоть десять пробелов. Чем меньше мы мешаем юзеру сделать как он хочет, тем лучше. Тримить их и спокойно создавать. То же и с почтой. Если он потом будет входить с пробелами — нестрашно. Я придерживался такой логики, когда дорабатывал валидацию

**Comment by fey** [comment]
Нуу обиднее больше когда пароль вроде бы нормальный, но копируешь-вставляешь его с пробелами, а потом он не подходит. Обсудим с продукт овнером. Вообще это не самое критичное, ибо щас даже банально пароль восстановить низзя, пользователей у нас не выглядит критично. 
Можно создать отдельный ишшус, там дискуссию вести. Подобные штуки мониторятся через всякие трекеры, которые отслеживают поведение пользователя (например яндекс метрика).

**Comment by faciledictu** [comment]
Ой, я перепутал issue и не туда написал про пробелы. Но пароль с пробелами не должен принимать, и он не принимает. Я про имя пользователя — его можно тримить

**Comment by bobrov-site** [comment]
@Yawerica вроде бы уже нет этой кнопки
