### ISSUE TITLE
Копия сниппета не соответствует оригиналу

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#483]
### Summary

Создается копия сниппета с шаблоном того сниппета, который открывался непосредственно перед созданием копии

### Reproduction steps

```bash
precondition:
1. Быть авторизованным.

steps:
1. Зайти на главную страницу https://runit.hexlet.ru/u/zzz
2. Создать сниппет-JS
3. Кликнуть кнопку Мои сниппеты

4. Создать сниппет-HTML
5. Кликнуть кнопку Мои сниппеты

6. Открыть созданный сниппет-JS
7. Кликнуть кнопку Мои сниппеты

8. Создать копию созданного сниппета-HTML через три точки
9. Убедиться, что копия сниппета-HTML создалась
```

### Expected result

Создалась копия сниппета-HTML

### Actual result

Создалась копия  сниппет-JS

https://github.com/hexlet-rus/runit/assets/148934630/676487c0-47ee-4692-abc3-21a2518e919c

Chrome

### OS

Linux

**Comment by Yawerica** [comment]
Uploading не соответствует копия (online-video-cutter.com).mp4…

**Comment by fey** [comment]
Я вижу, что вы копируете сниппет на HTML. А с JS сниппетом также будет? Можете еще посмотреть в девтулс, что отправляется? Есть подозрение, что устанавливается неверный язык.

**Comment by Yawerica** [comment]
![копия не аналог оригинала](https://github.com/hexlet-rus/runit/assets/148934630/103311ed-3cfc-4c54-b2f1-5086836b7caf)
это запрос, когда создаю копию JS-сниппета. 

да. для JS такая же проблема.

получается так, что копия, это всегда тот шаблон, который открывался до создания копии.

**Comment by Heaven-Tonight** [comment]
@fey, ага, при отправке запроса берется текущий язык из стейта, а надо брать язык конкретного сниппета, который копируем. Могу поправить)

**Comment by fey** [comment]
@Heaven-Tonight давайте

**Comment by Yawerica** [comment]
этот баг воспроизводится, потому что не было релиза? пока его не закрывать?

**Comment by fey** [comment]
Да, пока еще не приняли пулл реквест с изменениями и не задеплоили
