### ISSUE TITLE
Есть возможность другому пользователю редактировать сниппет по ссылке

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#484]
### Summary

Любой авторизованный пользователь может редактировать и сохранять изменения в сниппете по ссылке

### Reproduction steps

```bash
precondition:
1. Пользователь №1 авторизован
2. Пользователь №2 авторизован

steps:
1. Зайти на главную страницу https://runit.hexlet.ru/u/222222 как пользователь №1
2. Создать сниппет
3. Скопировать ссылку на созданный сниппет с помощью кнопки на самом сниппете
4. Зайти на главную страницу как Пользователь №2
5. В поисковую строку браузера вбить скопированную ссылку
6. В открывшийся сниппет внести изменения.
```

### Expected result

Пользователь №2 не может вносить изменения в чужой сниппет 

### Actual result

Пользователь №2 вносит изменения в сниппет и сохраняет их

https://github.com/hexlet-rus/runit/assets/148934630/983e0f8f-91b8-43e2-ab4c-35dddf5fa106

### Browsers

Chrome

### OS

Windows

**Comment by faciledictu** [comment]
Дубликат #346
