### ISSUE TITLE
Две одинаковые иконки(ссылки) на Телеграм в футере

### ISSUE THREAD

**Issue by Yawerica** [hexlet-rus/runit#485]
### Summary

Две одинаковые иконки(ссылки) на Телеграм в футере

### Reproduction steps

```bash
precondition:
1. Быть авторизованным.

steps:
1. Зайти а главную страницу https://runit.hexlet.ru/u/qqq1
2. Обратить внимание на иконки в разделе Подписаться
```

### Expected result

одинаковые иконки отсутствуют

### Actual result

![2 telegramma](https://github.com/hexlet-rus/runit/assets/148934630/4b765642-2a63-4e2b-b5b3-a1d53b3a52e7)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
Одна ссылка ведет на сообщество, другая на страницу Хекслета. Думаю сообщество можно убрать, и добавить ссылку что-то типа куда обращаться для поддержки. Как у кодбаттла - https://codebattle.hexlet.io/

![image](https://github.com/hexlet-rus/runit/assets/697178/78b73c9a-7e0d-49d8-af76-a24c77a98f90)

**Comment by bobrov-site** [comment]
Могу взять в работу

**Comment by fey** [comment]
Да давайте. Не забудьте демку, чтобы посмотреть, как будет выглядеть

**Comment by Yawerica** [comment]
@fey bug fixed.
@bobrov-site Thanks for your work.!

**Comment by bobrov-site** [comment]
@Yawerica дайте пожалуйста знать был ли исправлен баг? Если да, то закройте пожалуйста ишью
