### ISSUE TITLE
Починить верстку футера

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#488]
Посмотреть по коду старый вид и поправить футер. На скриншоте видно, что слиплись слова. Мб что-то криво удалили/изменили.

![image](https://github.com/hexlet-rus/runit/assets/697178/4b833ead-cd36-4eb1-8fbc-12e326fa08a9)

**Comment by fey** [comment]
@bobrov-site на втором скриншоте слепляется. Можете глянутЬ, как на основном Хекслете устроен футер, там много разного и он не слепляется (надеюсь что нет)

**Comment by bobrov-site** [comment]
@fey поправил. Там еще Косяк был с дублированием преимущества на втором скриншоте
<img width="389" alt="Снимок экрана 2024-05-28 в 22 24 06" src="https://github.com/hexlet-rus/runit/assets/39225852/78c23f32-4a62-42dc-b857-a38dfd905572">

**Comment by bobrov-site** [comment]
ну и еще раз футер с пк

![Uploading Снимок экрана 2024-05-28 в 22.27.40.png…]()

**Comment by bobrov-site** [comment]
<img width="2672" alt="Снимок экрана 2024-05-28 в 22 27 40" src="https://github.com/hexlet-rus/runit/assets/39225852/1067baea-727c-4035-96f6-8afe0743703d">

ну и еще раз футер с пк
