### ISSUE TITLE
Feature request: изменить верстку Лендинга под авторизованного пользователя 

### ISSUE THREAD

**Issue by bobrov-site** [hexlet-rus/runit#492]
### Problem description

Необходимо добавить реагирование приложения на то, что пользователь авторизован в системе в лендинге сайта. Когда заходишь на сайт, не очевидно, что ты уже авторизован на сайте. Тыкая на кнопку войти, словно играешь в русскую рулетку. Приятно когда авторизован, но когда сессия слетает, то не очень приятно не знать об этом заранее, потому что иногда быстрее тыкнуть на без регистрации, чтобы протестить быстро сниппет. 

### Proposed solution

Допустим пользователь авторизован, можно проблему решить 2 способами.

1. Если пользователь авторизован, добавить редирект на страницу со снипсетами
2. ИЛИ если пользователь авторизован изменить в лендинге следующее:

- Убрать кнопку кодить без регистрации с главной секции
- "Начать кодить" изменить на "перейти в профиль" или "перейти в сниппеты"
- Убрать кнопку регистрация с шапки

<img width="1450" alt="Снимок экрана 2024-05-30 в 21 52 15" src="https://github.com/hexlet-rus/runit/assets/39225852/4ce3bf04-b9c8-4826-a52a-4dbcd3d6f232">

Какой вариант лучше, думаю @fey подскажет.

**Comment by fey** [comment]
на самом деле лендинг нужен только для гостей, поэтому для авторизованных пользователей имеет смысл редиректить на страничку со сниппетами

**Comment by bobrov-site** [comment]
Могу взять в работу
