### ISSUE TITLE
Bug: Изменить шрифт надписи "Бесплатный проект Хекслета"

### ISSUE THREAD

**Issue by anastas250** [hexlet-rus/runit#496]
### Summary

Надпись "Бесплатный проект Хекслета" меняет шрифт в зависимости от типа устройства

### Reproduction steps

```bash
1. Открываем главную страницу https://runit.hexlet.ru/
2. Открываем DevTools
3. Открываем вкладку "Элементы"
4. Открываем панель инструментов устройства
5. Выбираем устройство на 375px
6. Выбираем устройство на 768px
7. Выбираем устройство на 1024px
```

### Expected result

Надпись "Бесплатный проект Хекслета" на всех устройствах выглядит одинаково

### Actual result

На устройстве от 1024px шрифт надписи "Бесплатный проект Хекслета" меняется на "Nunito Sans"

### Browsers

Chrome, Safari

### OS

Mac

**Comment by fey** [comment]
Да, возьмите. Какой-то странный баг. :thinking:
