### ISSUE TITLE
Bug: В разделе 'Карьера в Хекслете' в поле 'График работы' сортировка по возрастанию/убыванию не работает по алфавиту

### ISSUE THREAD

**Issue by Linchuki** [hexlet-rus/runit#505]
### Summary

В разделе 'Вакансии' сортировка в разделе 'Все, таблица' в поле 'График работы' сортировка "по возрастанию' и 'по убыванию' отображается не по алфавиту.
Значения 'Свободный' стоят не на своем месте при сортировке как в порядке возрастания (Ascending), так и в порядке убывания (Descending)

![График работы](https://github.com/hexlet-rus/runit/assets/151373511/79c173d1-3840-4891-9bca-4a2ed6b99d43)
![График работы-2](https://github.com/hexlet-rus/runit/assets/151373511/adbbcc08-e170-40ae-bca2-27e77dbf4657)
![График работы-3](https://github.com/hexlet-rus/runit/assets/151373511/01076708-684d-45f6-aaa1-cbd36c7f5fb4)

### Reproduction steps

```bash
1. Перейти по ссылке https://runit.hexlet.ru/
2. Прокрутить страницу до подвала
3. Нажать 'Карьера в Хекслете'
4. Открыть вкладку 'Все, таблица'
5. Нажать на значок со стрелочками справа над таблицей
6. Выбрать 'График работы'
7. Выбрать 'Descending'
8. Выбрать 'Ascending'
```

### Expected result

Значения в выбранном поле отсортированы по алфавиту в порядке возрастания.

### Actual result

Поле отсортировано не в алфавитном порядке как по возрастанию, так и по убыванию.

### Browsers

Chrome, Opera

### OS

Windows

**Comment by Linchuki** [comment]
Такая же проблема с колонкой 'Направление'.

![НАправление](https://github.com/hexlet-rus/runit/assets/151373511/b5790eac-de34-45d7-b370-72cd228f1a3e)

**Comment by bobrov-site** [comment]
А это точно относится к проекту Runit?

**Comment by fey** [comment]
Нет, это интерфейс ноушена)
