### ISSUE TITLE
Bug:  В таблице вакансий в колонке 'Занятость' сортировка по алфавиту работает наоборот

### ISSUE THREAD

**Issue by Linchuki** [hexlet-rus/runit#506]
### Summary

В разделе 'Карьера в Хекслете' в поле 'Занятость' сортировка по алфавиту  работает наоборот: вместо Ascending происходит Descending

### Reproduction steps

```bash
1. Перейти по ссылке https://runit.hexlet.ru/
2. Опуститься в подвал страницы
3. Нажать 'Карьера в Хекслете'
4. Открыть вкладку 'Все, таблица'
5. Нажать на значок со стрелочками справа над таблицей
6. Выбрать 'Занятость'
7. Выбрать 'Descending'
8. Выбрать 'Ascending'
```

### Expected result

Значения в выбранном поле отсортированы по алфавиту в порядке возрастания

### Actual result

Значения отсортированы по алфавиту в порядке убывания.

![Занятость](https://github.com/hexlet-rus/runit/assets/151373511/575c162f-8efc-4ac2-8db7-2cc7e758591f)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by bobrov-site** [comment]
Проблема в том, что все связанные issue относятся к Notion и не относятся к проекту Runit. Я бы вам посоветовал все данные замечания написать в телеграмме хекслета, в разделе обратная связь

**Comment by Linchuki** [comment]
Поняла, спасибо. Жаль, что тут не смогла помочь... А мне это хороший урок)

**Comment by bobrov-site** [comment]
По закрываете пожалуйста ишьюсы тогда, так как они не актуальны
