### ISSUE TITLE
Bug: Неровное отображение таблицы в разделе 'Карьера в Хекслете'

### ISSUE THREAD

**Issue by Linchuki** [hexlet-rus/runit#508]
### Summary

В разделе 'Карьера в Хекслете' таблица отображается криво: уходит за рамки экрана, в колонках не умещается текст

### Reproduction steps

```bash
1. Перейти по ссылке https://runit.hexlet.ru/
2. Опуститься в подвал страницы
3. Нажать 'Карьера в Хекслете'
4. Открыть вкладку 'Все, таблица'
5. Нажать на значок с двухсторонней стрелочкой 'Open as full page'
```

### Expected result

Таблица умещается в размеры экрана, текст в колонках не выходит за рамки ячеек.

### Actual result

Текст в колонках 'Направления' и 'Теги' выходит за рамки своих ячеек в таблице.
Можно сузить другие колонки, в которых много лишнего  свободного места и за счет этого расширить эти. Сделать отображение таблицы по ширине экрана.

![Полный экран](https://github.com/hexlet-rus/runit/assets/151373511/66cd434e-9f15-46e9-9593-d2d6f7767e3b)
![Полный экран-2](https://github.com/hexlet-rus/runit/assets/151373511/cbe33a1f-5c82-4395-b306-0dd32c9c4e64)

### Browsers

Chrome

### OS

Windows

**Comment by bobrov-site** [comment]
#506

**Comment by fey** [comment]
Интерфейс ноушена.
