### ISSUE TITLE
Bug: В разделе 'Карьера в Хекслете' значки над таблицей не переведены на русский язык

### ISSUE THREAD

**Issue by Linchuki** [hexlet-rus/runit#509]
### Summary

При наведении мышки на значки над таблицей в разделе 'Карьера в Хекслете', их описание отображается на английском языке, при том, что весь сайт - на русском.

### Reproduction steps

```bash
1. Перейти по ссылке https://runit.hexlet.ru/
2. Опуститься в подвал страницы
3. Нажать 'Карьера в Хекслете'
4. Открыть вкладку 'Все, таблица'
```

### Expected result

Значки  над таблицей (Фильтр, Сортировка, Поиск и другие) отображаются на русском языке.

### Actual result

Значки  над таблицей (Фильтр, Сортировка, Поиск и другие) отображаются на английском языке, хотя сайт открыт на русском языке.

![язык](https://github.com/hexlet-rus/runit/assets/151373511/55b92e0f-3dc7-494a-b787-bbe174b051a6)

### Browsers

Chrome

### OS

Windows

**Comment by Maiiiiiiiiia** [comment]
Привет! Я возьму в работу

**Comment by Maiiiiiiiiia** [comment]
Снимаюсь, тк это в ноушене же нужно изменения делать? это ссылка с сайта на ноушн

**Comment by bobrov-site** [comment]
#506

**Comment by Maiiiiiiiiia** [comment]
закройте этот issue тоже)

**Comment by fey** [comment]
Ага, это интерфейс ноушена, он не переведен.
