### ISSUE TITLE
Добавить предупредительные сообщения на ошибки

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#51]
**Проблема:**

В нашем проекте нет заглушек на ошибки, например на 404. 

**Какие шаги нужно воспроизвести:**
1. Ввести неккоректный Url - https://runit.hexlet.ru/hello
2. Увидим просто надпись "Страница не найдена"

**Как это сейчас:**

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/77053797/216079853-4496f495-b710-468b-971e-e1133dea2d9d.png">

**Как это должно работать:**
Должна выводится информация об ошибке и действия по ее устранению. 
Для примера можно взять https://ru.hexlet.io/mywef

Вставить "с главной" ссылку на https://runit.hexlet.ru/
В "в поддержку" вставить email runit@hexlet.io
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/77053797/216081202-73d35d63-4325-4741-98e2-939901dfcad0.png">

**Comment by Wenn911** [comment]
Какие ошибки ещё стоит добавить? 404 готова, ошибки авторизации тоже сделаны, 401 тоже есть.

**Comment by acidmaksim** [comment]
@Wenn911 Добавил?

**Comment by acidmaksim** [comment]
Задача свободна

**Comment by seregad544** [comment]
взял задачу
