### ISSUE TITLE
Bug: Ошибка верстки в группе ссылок в Footer

### ISSUE THREAD

**Issue by KseniyaKerzhner** [hexlet-rus/runit#511]
### Summary

При выборе размера устройства с шириной экрана от 443 до 991 px происходит ошибка верстки в группе ссылок "О нас" в footer.

![issue_17 06 24](https://github.com/hexlet-rus/runit/assets/34837694/3d0d324b-c3d4-4baf-b98d-00cf18e5ee71)

### Reproduction steps

```bash
1. Открыта страница https://runit.hexlet.ru
2. Открыть режим просмотра кода
3. Нажать "toggle device toolbar"
4. Выбрать устройство IPad Air
5. Опуститься в Footer страницы
```

### Expected result

Группа ссылок расположена вертикально отдна за одной с отступами

### Actual result

Группа ссылок расположена горизонтально без отступов

### Browsers

Chrome, Microsoft Edge

### OS

Windows

**Comment by bobrov-site** [comment]
Возьму в работу.

**Comment by bobrov-site** [comment]
@fey в этом же пуллреквесте предлагаю сместить номера на строку с навигацией футера, как на скриншоте. А то, с 992, до 1199 получается как на скриншоте не очень.
<img width="1303" alt="Снимок экрана 2024-06-20 в 13 40 13" src="https://github.com/hexlet-rus/runit/assets/39225852/41a3d274-9006-4aaa-b092-07bd546e360e">

**Comment by fey** [comment]
@bobrov-site попробуйте) Можно еще за основу взять футер основного Хекслета, но нужно учитывать, что он очень большой. https://ru.hexlet.io

**Comment by bobrov-site** [comment]
@KseniyaKerzhner  Баг все еще актуален?

**Comment by KseniyaKerzhner** [comment]
@bobrov-site Да, на той неделе смотрела было вроде всё хорошо, хотела закрыть, но увидела что баг опять вернулся

**Comment by bobrov-site** [comment]
Странно, гляну. Возможно на мастере что-то не то. А условия те же в баге?

**Comment by KseniyaKerzhner** [comment]
ага, условия те же. И ещё один баг вернулся #458, тоже был пофикшен и опять появился. Может они как то связаны?

**Comment by fey** [comment]
Ребят, runit деплоится вручную, по тегам, поэтому может быть такое, что в главной ветке есть изменения, а на продакшене еще нет. Сейчас заделпою
