### ISSUE TITLE
Bug: Не работает загрузка изображения в настройках учетной записи

### ISSUE THREAD

**Issue by KseniyaKerzhner** [hexlet-rus/runit#515]
### Summary

При изменении изображения в настройках учетной записи картинка не заггружается и изменений не происходит.

### Reproduction steps

```bash
1. Пользователь должен быть авторизован
2. Выбрать в меню пункт "Настройки"
3. Нажать "Изменить" под изображением пользователя
4. Нажать "Выберите файл" и выбрать изображение в формате jpeg или png
5. Нажать "Загрузить"
```

### Expected result

Изображение изменено.

### Actual result

Изменений не происходит, изображение не меняется.

### Browsers

Chrome

### OS

Windows

**Comment by bobrov-site** [comment]
Это не баг. Фича не была доделана. Работа в ней упомянута в #418 . Там нужно с бэком разобраться.

**Comment by KseniyaKerzhner** [comment]
Хорошо. Тогда закрою.
