### ISSUE TITLE
Bug:  One of the links in the "Documents" section is missing in the English version

### ISSUE THREAD

**Issue by KseniyaKerzhner** [hexlet-rus/runit#517]
### Summary

In the English version of the authorized user, there is no "Non-commercial license agreement" link in the Footer section "Documents". 

![image](https://github.com/hexlet-rus/runit/assets/34837694/aa71e0ef-74f9-4531-87cf-797de275ff58)

### Reproduction steps

```bash
1. User authorized
2. Scroll down to Footer
```

### Expected result

There is a link "Non-commercial license agreement" as in the Russian version.

### Actual result

There is no "Non-commercial license agreement" link.

### Browsers

Chrome

### OS

Windows

**Comment by Dmitry1399** [comment]
I take this issue

**Comment by KseniyaKerzhner** [comment]
Fixed.
