### ISSUE TITLE
Bug: Media query error on the main page in the mobile version in horizontal position

### ISSUE THREAD

**Issue by KseniyaKerzhner** [hexlet-rus/runit#518]
### Summary

On the main page in the mobile version, when you rotate the screen horizontally, the background picture disappears and the title "INSTANT IDE" in two lines does not look correct.

And in the mobile version, I would drop the sentence "Write code directly in the browser!" lower down to the next line.

https://github.com/hexlet-rus/runit/assets/34837694/62730f52-e3bb-428b-8a32-9b28b8807d15

### Reproduction steps

```bash
1. Home page is open
2. Open code view mode
3. Press "toggle device toolbar"
4. Select a Pixel 7 device
5. Turn horizontally
```

### Expected result

The background displays the same as on mobile with blue bars and a single line header

### Actual result

The background became just white/black and the header is reflected on two lines

### Browsers

Chrome

### OS

Windows

**Comment by Dmitry1399** [comment]
I take this issue

**Comment by fey** [comment]
@KseniyaKerzhner did it fixed?

**Comment by KseniyaKerzhner** [comment]
Checked, yes, it's fixed.
