### ISSUE TITLE
Bug: No menu in the footer on mobile version

### ISSUE THREAD

**Issue by KseniyaKerzhner** [hexlet-rus/runit#523]
### Summary

The mobile version is missing the menu in the footer.

![Screenshot_20240628-180352](https://github.com/hexlet-rus/runit/assets/34837694/39e3b3e0-ece7-44c9-81c4-b4fcfadeb3cc)

### Reproduction steps

```bash
1. Go to the main page
```

### Expected result

There is menu just like the desktop version.

### Actual result

There is no menu.

### Browsers

Chrome

### OS

Windows

**Comment by Mehdi-Messaadi** [comment]
Hello!
I'd like to take this issue, please.
