### ISSUE TITLE
Bug: Hexlet Friends page is not working

### ISSUE THREAD

**Issue by sergiozeppo** [hexlet-rus/runit#533]
### Summary

I noticed that in the README of the Runit project there is a link to the most active contributors and wanted to familiarize myself with it. 
However, the page does not work. 

### Reproduction steps

```bash
1. Go to "https://github.com/hexlet-rus/runit/blob/main/README.md"
2. Scroll down right to the bottom
3. See the phrase "See most active contributors on hexlet-friends."
4. Click on the link. 
5. See the error.
```

### Expected result

Opening the page

### Actual result

The page is not working. 
See the screenshot
![image](https://github.com/user-attachments/assets/75964bbc-c322-45d9-bf61-fe7d718a73f0)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
It looks like we have a floating bug, seemingly related to loading data from the database

**Comment by sergiozeppo** [comment]
> It looks like we have a floating bug, seemingly related to loading data from the database

Seems to be true. Maybe I open the friends page in inappropriate time) 
But after creating the issue i met this bug maybe 4-5 times. 
Of course, I think, that it's not so popular page, but maybe need to replace this error page to smthn like "Data is updating, please wait..."
But, of course, it's up to you. 
If you want to, you can close issue.

**Comment by fey** [comment]
We need to work on improving the queries, maybe something is being loaded inappropriately. I'll create a task for our developer to upload data that you could use locally
