### ISSUE TITLE
Bug: no footer on the mobile version of the site

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#535]
### Summary

![image](https://github.com/user-attachments/assets/d5a6e8df-7e04-48a9-aa05-e51efc14334b)
![image](https://github.com/user-attachments/assets/010c5c09-9e6c-45b5-a934-89cfecc54b64)

### Reproduction steps

```bash
1. open runit.hexlet.ru on mobile mode
2. scroll down
```

### Expected result

Footer is visible

### Actual result

No footer

### Browsers

Chrome

### OS

Linux

**Comment by IVANn84** [comment]
hello! Can I take this task? I'm just warning you, I'm a beginner and I can do a little long).

**Comment by fey** [comment]
@IVANn84 yes, you can!

**Comment by KseniyaKerzhner** [comment]
I reported this bug in issue #523 as well.

**Comment by IVANn84** [comment]
I take it the task has already been solved? pull request is merged..

**Comment by Mehdi-Messaadi** [comment]
Hi!
Yes, I believe the task has already been solved and the PR merged into the main branch.

**Comment by fey** [comment]
ok, i will check

**Comment by fey** [comment]
deployed new version. Now looks well :+1: Thank you!
