### ISSUE TITLE
Bug: When copying snippets several times in a row, the word "copy" in the title stops being fully visible.

### ISSUE THREAD

**Issue by ViktorSmiryagin** [hexlet-rus/runit#541]
---

### Summary

When copying snippets sequentially, the word "copy" is not fully displayed. A possible solution is to add numbering to the copies or display the full snippet name on hover. Example: Test_code, Test_code copy, Test_code copy(2), and so on.

<img width="1408" alt="Screenshot 2024-08-19 at 00 23 52" src="https://github.com/user-attachments/assets/0960a870-1aa8-4654-b905-79d37c58ed8a">

### Reproduction Steps

```bash
0. Ensure the user is logged in.
1. Create a snippet.
2. Click the "Save" button.
3. Go to the "My Snippets" section.
4. Make a copy of the last saved snippet (without changing its name).
5. Repeat steps 2-4 several times (4-5 times).
```

### Expected Result

The name of each copied snippet should be fully displayed.

### Actual Result

The snippet name exceeds the visible field boundary, and the word "copy" is not visible.

<img width="368" alt="Screenshot 2024-08-19 at 00 30 37" src="https://github.com/user-attachments/assets/59562eb0-c9b2-468e-813d-65aedc77bfa6">

### Browsers

Chrome

### OS

Mac

---

**Comment by bobrov-site** [comment]
@ViktorSmiryagin please rename your issue and change description for this tusk, because have new requirements from this ticket #527 

By the way, I can handle this tusk. I will get the task

**Comment by ViktorSmiryagin** [comment]
Hello, done) good luck with your work)

Сб, 24 авг. 2024 г. в 22:04, Daniil Bobrov ***@***.***>:
