### ISSUE TITLE
Bug: Company Logo on Website is Outdated Compared to Updated Logo on Twitter 

### ISSUE THREAD

**Issue by ViktorSmiryagin** [hexlet-rus/runit#548]
### Summary

The company's website displays an outdated logo, while the official Twitter account uses a new logo. This discrepancy in branding could confuse users.

Attachments:

Screenshot of the old Twitter logo in the website footer.
<img width="1296" alt="Screenshot 2024-08-26 at 12 35 56" src="https://github.com/user-attachments/assets/b2948a50-dd3b-49ec-a46d-4a6d437404b7">

Screenshot of the new Twitter logo from the Twitter profile.
<img width="817" alt="Screenshot 2024-08-26 at 12 37 04" src="https://github.com/user-attachments/assets/5fc2e75f-de0d-404e-a0a9-a44670098022">

### Reproduction steps

```bash
1. Open the website https://runit.hexlet.ru.
2. Scroll down to the footer section containing links to social media platforms (Twitter, Instagram, YouTube).
3. Compare the Twitter logo displayed in the footer with the new logo on the company’s Twitter profile.
```

### Expected result

The logo in the website footer should match the new logo used on the company’s official Twitter("X") social network.

### Actual result

The website displays the old Twitter logo in the footer section.

### Browsers

Chrome

### OS

Mac

**Comment by PavelKochetkov** [comment]
Sent a pull request

**Comment by sergiozeppo** [comment]
Close the issue as completed, please.
