### ISSUE TITLE
Bug: Snapshot Copy Confirmation Button Shows Russian Text in English Version of Site

### ISSUE THREAD

**Issue by ViktorSmiryagin** [hexlet-rus/runit#549]
### Summary

When switching to the English version of the site, the "confirm" button in the popup window for copying a snippet is still displayed in Russian
Precondition:

1. User is logged in
2. Ensure that the English version of the site is selected
3. There are previously created snippets
<img width="1567" alt="Screenshot 2024-09-01 at 00 50 37" src="https://github.com/user-attachments/assets/31326a40-95bc-47b7-a9ad-8a7f43204921">

### Reproduction steps

```bash
1. Open the snippet menu
2. Click the button to copy the snippet
```

### Expected result

The popup window that appears should display all text, including the "confirm" button, in English.

### Actual result

The "confirm" button is displayed in Russian, even when the site is set to English

### Browsers

Chrome

### OS

Mac

**Comment by PavelKochetkov** [comment]
Sent a pull request

**Comment by ViktorSmiryagin** [comment]
@fey Need to reopen this issue because it isn’t fixed 
<img width="1395" alt="Screenshot 2024-09-13 at 13 15 05" src="https://github.com/user-attachments/assets/6ded22fc-3ba1-4310-bd24-3d0f9edb133a">

**Comment by fey** [comment]
@ViktorSmiryagin yea, it coz PR was merged with mention this issue. But i didnot deployed yea

**Comment by fey** [comment]
![image](https://github.com/user-attachments/assets/9df15edc-750f-4499-89ca-432e275ec706)
