### ISSUE TITLE
Add support of new languages without code running

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#550]
### Problem description

We have HTML and JS that can run. But we should add new languages. We can do it without running code, simple code snippets

### Proposed solution

Add support of code saving and highlights for

* php
* java
* python

and other

**Comment by Reyka141** [comment]
Can I take this job?

**Comment by HelenOne** [comment]
@Reyka141

**Comment by Reyka141** [comment]
I send pull request #561, please check
