### ISSUE TITLE
Bug: Incorrect display of the name of the "login" button in the menu for an unauthorized user

### ISSUE THREAD

**Issue by PavelKochetkov** [hexlet-rus/runit#553]
### Summary

When opening the menu for an unauthorized user, the name of the login button is displayed incorrectly

### Reproduction steps

```bash
1. Go to the website https://runit.hexlet.ru/
2. Click "Try without registration"
3. Select the "JavaScript" template
4. Click the "Create" button
5. Open menu
```

### Expected result

The button name is displayed correctly for both Russian and English localization

### Actual result

The button name is not displayed correctly for both Russian and English localization
![Screenshot_14](https://github.com/user-attachments/assets/0107b97b-fdc5-4c98-a86c-d3a9ce7fc2c0)
![Screenshot_15](https://github.com/user-attachments/assets/17b98a5a-e13b-4533-b14d-f60cc1cd0650)

### Browsers

Chrome

### OS

Windows

**Comment by mad-chameleon** [comment]
Fixed:  https://github.com/hexlet-rus/runit/pull/554

Deploy: https://mad-chameleon-runit.onrender.com/

**Comment by fey** [comment]
@sergiozeppo not deployed yeat

**Comment by fey** [comment]
deployed
