### ISSUE TITLE
Bug: Old Twitter logo in the Footer

### ISSUE THREAD

**Issue by sergiozeppo** [hexlet-rus/runit#558]
### Summary

Hi there, Hexlet team!
Noticed that currently in the Footer we have an old Twitter icon.  
![изображение](https://github.com/user-attachments/assets/bd8e5d81-410e-42e4-b8d5-310dd5a557af)

### Reproduction steps

```bash
1. Go to any page, f.e. "About"
2. Go down to the bottom of the page
3. Notice the old Twitter logo.
```

### Expected result

A new X-shaped logo

### Actual result

old logo

### Browsers

Firefox, Chrome

### OS

Windows, Linux

**Comment by Polyquid** [comment]
Hello!

I'll take the job
