### ISSUE TITLE
Edit footer

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#66]
Delete what is highlighted in red. 
In the green block - insert a link to the main Hexlet, at the top - [Хекслет](http://hexlet.io/)
![image](https://user-images.githubusercontent.com/77053797/202210582-f2f1678c-d265-4272-b1ab-baf7b524dfa9.png)

And add a footer on landing

**Comment by Wenn911** [comment]
Возьму в работу

**Comment by acidmaksim** [comment]
Смести "Наши проекты" влево, а подписать под "Хекслет-резюме"
