### ISSUE TITLE
You need to fix the delete/rename button

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#67]
The cards now cover that button. For example, you can make three dots in the upper right corner of the card

![image](https://user-images.githubusercontent.com/77053797/202367980-3c6ca998-d891-42ce-9af0-2a6ef914e788.png)

**Comment by gogoiakash2311** [comment]
Help me to locate this issue on the website

**Comment by userao** [comment]
Я беру в работу
