### ISSUE TITLE
 Add the "make build" command to the readme

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#68]

**Comment by kaamosdao** [comment]
Можно еще добавить в пункт "Запуск приложения в режиме разработки" команду "make start-frontend". Сейчас обновления подгружаются и вебпак пересобирает проект, когда в другой вкладке выполнен "make start-frontend", только нужно страницу обновлять.

**Comment by ashikov** [comment]
@dzencot вполне разумное предложение добавить команду `make start-frontend` в ридми. Как думаешь?

**Comment by dzencot** [comment]
Да, конечно, давайте добавим
