### ISSUE TITLE
Не работает восстановление пароля

### ISSUE THREAD

**Issue by fey** [hexlet-rus/runit#94]
https://runit.hexlet.ru/remind_password
При нажатии на кнопку ничего не происходит.

Письмо должно приходить от info@runit.hexlet.ru

- [x] https://github.com/hexlet-rus/runit/issues/355

**Comment by svyatoslavxq** [comment]
Беру в работу

**Comment by svyatoslavxq** [comment]
@fey а восстановление пароля вообще было реализовано?) Там на 21 строке емейл просто выводится в консоль https://github.com/hexlet-rus/runit/blob/main/app/javascript/Pages/RemindPassword.jsx

**Comment by fey** [comment]
Ну, надо реализовать значит))

**Comment by svyatoslavxq** [comment]
отказываюсь, не смогу выполнить

**Comment by EgorUlitin** [comment]
@fey а есть апи для этого дела какое-нибудь? отправка мейла же не с фронта происходит?

**Comment by acidmaksim** [comment]
@dzencot подскажи, пожалуйста

**Comment by fey** [comment]
Скорее всего апишки нет и внешний сервис не используется.
Т.е. если будет делаться отправка письма, нужно предусмотреть возможность использовать отправку писем со внешнего сервиса, типа sparkpost и должно это работать через переменные окружения (т.е. креды от почты, что использовать для отправки писем, потому что для разработки локально не нужно в реальности отправлять письма)

**Comment by dzencot** [comment]
Готового апи нет. Нужно добавить в express сервис отправки писем, как Коля выше написал

**Comment by LarendsD** [comment]
Мы с @Takaiva, планируем заняться этой задачей на выходных, есть уже какой-то дизайн письма отправляемой почты в фигме?

**Comment by acidmaksim** [comment]
@LarendsD давай пока будем ссылаться на шаблон восставнолвения из Хекслета. Только Хекслет нужно заменить на RunIT и **обязательно** должна быть возможность отписаться от рассылки
![image](https://user-images.githubusercontent.com/77053797/217497196-177de5a5-5e17-4e8e-bb26-c425664569f7.png)

**Comment by LarendsD** [comment]
@acidmaksim, хорошо, понял

**Comment by LarendsD** [comment]
К сожалению, у @Takaiva не выходит никак по планам, поэтому нужен фронтендер который всё это подлючит на фронте к беку. Только единственное нужно будет связаться чтобы по апи объяснить

**Comment by likurg42** [comment]
Беру фронтенед часть задачи в работу

**Comment by margo-yunanova** [comment]
@fey, привет,  тут ещё требуется что-то по фронтенду делать?

**Comment by fey** [comment]
@margo-yunanova по фронтенду кажется нет, осталось подключить апи.

**Comment by faciledictu** [comment]
Ну по сути подключить спи — это доработать отправку формы, то есть работа с фронтендом. Я вижу, что на бэке реализована отправка. Или там что-то не работает?

**Comment by fey** [comment]
Я креды добавлял на продакщен. Локально должен использоваться специальный сервис. 
Посмотрите по коду, работает ли отправка на апи.

**Comment by fey** [comment]
@margo-yunanova для восстановления пароля у нас два метода. 
Первый - это https://runit.hexlet.ru/api#/users/UsersController_recover 
для того, чтобы запросить письмо,
второй - как раз с хешем. Бекенд должен сравнить хеш. Но кажется да, - https://github.com/hexlet-rus/runit/issues/355
не доделано на бекенде 🤔

**Comment by faciledictu** [comment]
@margo-yunanova Бэкенд надо дописывать. Ишью #355 — это, по сути, дубль этого ишью, но по резуальтатам обсуждения с @dzencot. Там две задачи, на бэк и фронт.

**Comment by dzencot** [comment]
Сергей вроде взял в работу. Если нужно сделать бэк, я добавлю

**Comment by LarendsD** [comment]
Бэк сделан ведь, проверка на актуальность хэша там есть, если хэш не актуален, то отдается ответ с объектом id: null, максимум что можно сделать так это переделать на выброс ошибки, но имеет ли смысл

**Comment by fey** [comment]
@LarendsD можете описать флоу работы. Начиная от "пользователь нажал кнопку восстановить пароль", до собственно смены пароля?

**Comment by LarendsD** [comment]
@fey конечно 
1. Пользователь заходит на страницу восстановления пароля, где вводит свой email
2. Далее идет запрос на сервер с урлом фронтенда(frontendUrl) и с самим емейлом(email) на POST users/recover
3. На сервере емейл шифруется в хэш и с помощью этого хэша формируется ссылка на страницу восстановления пароля(например `${frontendUrl}/recovery/${revoverHash}`) и отправляется на емейл пользователя. Вместе с этим хэш вносится в таблицу users в колонку recover_hash, также ставится setTimeout на 15 минут по истечению которого хэш из таблицы очищается
4. На почте пользователь проходит по ссылке в письме и происходит следующее:
4.1. Фронт достает из ссылки хэш
4.2. Идет запрос с фронтенда на сервер GET users/recover/:hash, где хэш  расшифровывается и по полученному емейлу из хэша идет поиск пользователя в базе, если пользователь найден и хэши в базе совпадают, то отдается id пользователя, иначе отдается { id: null }
4.3. После получения ответа от сервера фронтенд отображает страницу со сменой пароля, если id не null, иначе отображает страницу с сообщением что-то в духе 'Срок ссылки истек'
4.4. На странице со сменой пароля после ввода нового пароля происходит запрос на сервер PUT /users/:id где как раз и происходит смена самого пароля

**Comment by fey** [comment]
вот где-то в конце у нас есть трабла. По идее смена пароля не должна быть привязана к обновлению самого юзера. 

По идее должно быть как - пользователь запрашивает восстановление - POST запрос. 
Отправляется письмо с хешом на емейл. 
Ссылка (хеш) действительна какое-то время.
Пользователь открывает ссылку на фронте, фротенд валидирует хеш на бекенде. Если все ок - выводится форма, в ней форма ввода пароля. 
Когда пароль меняется, отправляется пароль + хеш для смены пароля. 

Просто щас есть проблема в безопасности по смене пароля (есть репорт, ищщус наверное не показывается).
