### ISSUE TITLE
Edit footer

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#95]
Swap columns
![image](https://user-images.githubusercontent.com/77053797/204547921-cbe28583-a208-4f73-afba-190ec089583a.png)

**Comment by Difuster** [comment]
Беру в работу

**Comment by denikeev** [comment]
@acidmaksim 
сейчас футер выглядит так:
![image](https://user-images.githubusercontent.com/46960223/209815379-8db5a7c2-c184-4d9b-af92-3b7cc84ad886.png)

ты предлагаешь такой порядок? :
![image](https://user-images.githubusercontent.com/46960223/209815519-09d6b964-0919-4bd8-9dcd-39f2fac4ca34.png)
