### ISSUE TITLE
Предложения по доработке верстки

### ISSUE THREAD

**Issue by rinat-lucky** [hexlet-rus/runit#98]
- [ ] на главной странице добавить отступы до и после флекс-контейнера (см. скрин 1)
- [x] #100

![1](https://user-images.githubusercontent.com/64750426/204924903-4db36d32-d8d2-4ec3-9681-013f8618f977.jpg)
![2](https://user-images.githubusercontent.com/64750426/204924916-0484dfc8-7c3b-475d-8961-cd94d35f971e.jpg)

**Comment by denikeev** [comment]
по первой таске, на данный момент отступы уже есть
