### ISSUE TITLE
Добавить отступ у кнопки  и текста

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-rus/runit#99]
Сейчас кнопка прилипла к тексту и выглядит не очень хорошо, нужно добавить небольшой отступ. 

![image](https://user-images.githubusercontent.com/77053797/205006746-cf34ad82-ab5c-42ae-a728-87282722e87d.png)

Текст "Пишите код прямо в браузере!" тоже очень близко к блокам и ему нужно добавить отступ. 

![image](https://user-images.githubusercontent.com/77053797/205007663-32896cb8-f22e-4e92-ad8d-4c09c6541b58.png)

**Comment by svyatoslavxq** [comment]
Беру в работу
